// Code generated by ent, DO NOT EDIT.

package oauthrefreshfamily

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldCreatedAt, v))
}

// FamilyID applies equality check predicate on the "family_id" field. It's identical to FamilyIDEQ.
func FamilyID(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldFamilyID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldUserID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldClientID, v))
}

// Generation applies equality check predicate on the "generation" field. It's identical to GenerationEQ.
func Generation(v int) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldGeneration, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldIssuedAt, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldRevoked, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLTE(FieldCreatedAt, v))
}

// FamilyIDEQ applies the EQ predicate on the "family_id" field.
func FamilyIDEQ(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldFamilyID, v))
}

// FamilyIDNEQ applies the NEQ predicate on the "family_id" field.
func FamilyIDNEQ(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNEQ(FieldFamilyID, v))
}

// FamilyIDIn applies the In predicate on the "family_id" field.
func FamilyIDIn(vs ...string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldIn(FieldFamilyID, vs...))
}

// FamilyIDNotIn applies the NotIn predicate on the "family_id" field.
func FamilyIDNotIn(vs ...string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNotIn(FieldFamilyID, vs...))
}

// FamilyIDGT applies the GT predicate on the "family_id" field.
func FamilyIDGT(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGT(FieldFamilyID, v))
}

// FamilyIDGTE applies the GTE predicate on the "family_id" field.
func FamilyIDGTE(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGTE(FieldFamilyID, v))
}

// FamilyIDLT applies the LT predicate on the "family_id" field.
func FamilyIDLT(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLT(FieldFamilyID, v))
}

// FamilyIDLTE applies the LTE predicate on the "family_id" field.
func FamilyIDLTE(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLTE(FieldFamilyID, v))
}

// FamilyIDContains applies the Contains predicate on the "family_id" field.
func FamilyIDContains(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldContains(FieldFamilyID, v))
}

// FamilyIDHasPrefix applies the HasPrefix predicate on the "family_id" field.
func FamilyIDHasPrefix(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldHasPrefix(FieldFamilyID, v))
}

// FamilyIDHasSuffix applies the HasSuffix predicate on the "family_id" field.
func FamilyIDHasSuffix(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldHasSuffix(FieldFamilyID, v))
}

// FamilyIDEqualFold applies the EqualFold predicate on the "family_id" field.
func FamilyIDEqualFold(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEqualFold(FieldFamilyID, v))
}

// FamilyIDContainsFold applies the ContainsFold predicate on the "family_id" field.
func FamilyIDContainsFold(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldContainsFold(FieldFamilyID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldContainsFold(FieldUserID, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldContainsFold(FieldClientID, v))
}

// GenerationEQ applies the EQ predicate on the "generation" field.
func GenerationEQ(v int) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldGeneration, v))
}

// GenerationNEQ applies the NEQ predicate on the "generation" field.
func GenerationNEQ(v int) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNEQ(FieldGeneration, v))
}

// GenerationIn applies the In predicate on the "generation" field.
func GenerationIn(vs ...int) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldIn(FieldGeneration, vs...))
}

// GenerationNotIn applies the NotIn predicate on the "generation" field.
func GenerationNotIn(vs ...int) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNotIn(FieldGeneration, vs...))
}

// GenerationGT applies the GT predicate on the "generation" field.
func GenerationGT(v int) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGT(FieldGeneration, v))
}

// GenerationGTE applies the GTE predicate on the "generation" field.
func GenerationGTE(v int) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGTE(FieldGeneration, v))
}

// GenerationLT applies the LT predicate on the "generation" field.
func GenerationLT(v int) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLT(FieldGeneration, v))
}

// GenerationLTE applies the LTE predicate on the "generation" field.
func GenerationLTE(v int) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLTE(FieldGeneration, v))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLTE(FieldIssuedAt, v))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNEQ(FieldRevoked, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.FieldNotNull(FieldRevokedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthRefreshFamily) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthRefreshFamily) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthRefreshFamily) predicate.OAuthRefreshFamily {
	return predicate.OAuthRefreshFamily(sql.NotPredicates(p))
}
