// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DocumentsColumns holds the columns for the "documents" table.
	DocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "overview", Type: field.TypeString, Size: 2147483647},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "content_type", Type: field.TypeString, Default: "text/markdown"},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "change_comment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "document_created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "document_updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "project_documents", Type: field.TypeUUID},
	}
	// DocumentsTable holds the schema information for the "documents" table.
	DocumentsTable = &schema.Table{
		Name:       "documents",
		Columns:    DocumentsColumns,
		PrimaryKey: []*schema.Column{DocumentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "documents_users_created_by",
				Columns:    []*schema.Column{DocumentsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "documents_users_updated_by",
				Columns:    []*schema.Column{DocumentsColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "documents_projects_documents",
				Columns:    []*schema.Column{DocumentsColumns[13]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "document_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[2]},
			},
		},
	}
	// DocumentSnapshotsColumns holds the columns for the "document_snapshots" table.
	DocumentSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "version", Type: field.TypeInt},
		{Name: "overview", Type: field.TypeString, Size: 2147483647},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "comment", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "document_snapshots", Type: field.TypeUUID},
		{Name: "document_snapshot_created_by", Type: field.TypeUUID, Nullable: true},
	}
	// DocumentSnapshotsTable holds the schema information for the "document_snapshots" table.
	DocumentSnapshotsTable = &schema.Table{
		Name:       "document_snapshots",
		Columns:    DocumentSnapshotsColumns,
		PrimaryKey: []*schema.Column{DocumentSnapshotsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "document_snapshots_documents_snapshots",
				Columns:    []*schema.Column{DocumentSnapshotsColumns[7]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "document_snapshots_users_created_by",
				Columns:    []*schema.Column{DocumentSnapshotsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OauthAuthCodesColumns holds the columns for the "oauth_auth_codes" table.
	OauthAuthCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "client_id", Type: field.TypeString},
		{Name: "redirect_uri", Type: field.TypeString},
		{Name: "scope", Type: field.TypeString, Nullable: true},
		{Name: "resource", Type: field.TypeString, Nullable: true},
		{Name: "audience", Type: field.TypeString, Nullable: true},
		{Name: "code_challenge", Type: field.TypeString, Nullable: true},
		{Name: "code_challenge_method", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "provider_token", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "used", Type: field.TypeBool, Default: false},
	}
	// OauthAuthCodesTable holds the schema information for the "oauth_auth_codes" table.
	OauthAuthCodesTable = &schema.Table{
		Name:       "oauth_auth_codes",
		Columns:    OauthAuthCodesColumns,
		PrimaryKey: []*schema.Column{OauthAuthCodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthauthcode_expires_at",
				Unique:  false,
				Columns: []*schema.Column{OauthAuthCodesColumns[12]},
			},
		},
	}
	// OauthAuthStatesColumns holds the columns for the "oauth_auth_states" table.
	OauthAuthStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "state_id", Type: field.TypeString, Unique: true},
		{Name: "original_client_state", Type: field.TypeString, Nullable: true},
		{Name: "client_id", Type: field.TypeString},
		{Name: "redirect_uri", Type: field.TypeString},
		{Name: "scope", Type: field.TypeString, Nullable: true},
		{Name: "resource", Type: field.TypeString, Nullable: true},
		{Name: "code_challenge", Type: field.TypeString, Nullable: true},
		{Name: "code_challenge_method", Type: field.TypeString, Nullable: true},
		{Name: "provider_state", Type: field.TypeString, Unique: true},
		{Name: "provider_code_verifier", Type: field.TypeString},
		{Name: "nonce", Type: field.TypeString, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// OauthAuthStatesTable holds the schema information for the "oauth_auth_states" table.
	OauthAuthStatesTable = &schema.Table{
		Name:       "oauth_auth_states",
		Columns:    OauthAuthStatesColumns,
		PrimaryKey: []*schema.Column{OauthAuthStatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthauthstate_expires_at",
				Unique:  false,
				Columns: []*schema.Column{OauthAuthStatesColumns[13]},
			},
		},
	}
	// OauthClientsColumns holds the columns for the "oauth_clients" table.
	OauthClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "client_id", Type: field.TypeString, Unique: true},
		{Name: "client_secret_hash", Type: field.TypeString},
		{Name: "client_type", Type: field.TypeString},
		{Name: "redirect_uris", Type: field.TypeJSON},
		{Name: "token_endpoint_auth_method", Type: field.TypeString},
		{Name: "grant_types", Type: field.TypeJSON},
		{Name: "response_types", Type: field.TypeJSON},
		{Name: "client_name", Type: field.TypeString},
		{Name: "scopes", Type: field.TypeJSON},
		{Name: "registration_access_token_hash", Type: field.TypeString, Nullable: true},
		{Name: "registration_ip", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OauthClientsTable holds the schema information for the "oauth_clients" table.
	OauthClientsTable = &schema.Table{
		Name:       "oauth_clients",
		Columns:    OauthClientsColumns,
		PrimaryKey: []*schema.Column{OauthClientsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthclient_registration_ip",
				Unique:  false,
				Columns: []*schema.Column{OauthClientsColumns[12]},
			},
		},
	}
	// OauthConsentsColumns holds the columns for the "oauth_consents" table.
	OauthConsentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
		{Name: "client_id", Type: field.TypeString},
		{Name: "client_name", Type: field.TypeString},
		{Name: "granted_at", Type: field.TypeTime},
	}
	// OauthConsentsTable holds the schema information for the "oauth_consents" table.
	OauthConsentsTable = &schema.Table{
		Name:       "oauth_consents",
		Columns:    OauthConsentsColumns,
		PrimaryKey: []*schema.Column{OauthConsentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthconsent_user_id_client_id",
				Unique:  true,
				Columns: []*schema.Column{OauthConsentsColumns[2], OauthConsentsColumns[3]},
			},
		},
	}
	// OauthKeysColumns holds the columns for the "oauth_keys" table.
	OauthKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "singleton", Type: field.TypeInt, Unique: true},
		{Name: "ec_private_key_pem", Type: field.TypeString},
		{Name: "kid", Type: field.TypeString},
		{Name: "master_secret", Type: field.TypeString},
	}
	// OauthKeysTable holds the schema information for the "oauth_keys" table.
	OauthKeysTable = &schema.Table{
		Name:       "oauth_keys",
		Columns:    OauthKeysColumns,
		PrimaryKey: []*schema.Column{OauthKeysColumns[0]},
	}
	// OauthProviderTokensColumns holds the columns for the "oauth_provider_tokens" table.
	OauthProviderTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "token_json", Type: field.TypeString, Size: 2147483647},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OauthProviderTokensTable holds the schema information for the "oauth_provider_tokens" table.
	OauthProviderTokensTable = &schema.Table{
		Name:       "oauth_provider_tokens",
		Columns:    OauthProviderTokensColumns,
		PrimaryKey: []*schema.Column{OauthProviderTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthprovidertoken_expires_at",
				Unique:  false,
				Columns: []*schema.Column{OauthProviderTokensColumns[4]},
			},
		},
	}
	// OauthRefreshFamiliesColumns holds the columns for the "oauth_refresh_families" table.
	OauthRefreshFamiliesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "family_id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "client_id", Type: field.TypeString},
		{Name: "generation", Type: field.TypeInt},
		{Name: "issued_at", Type: field.TypeTime},
		{Name: "revoked", Type: field.TypeBool, Default: false},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
	}
	// OauthRefreshFamiliesTable holds the schema information for the "oauth_refresh_families" table.
	OauthRefreshFamiliesTable = &schema.Table{
		Name:       "oauth_refresh_families",
		Columns:    OauthRefreshFamiliesColumns,
		PrimaryKey: []*schema.Column{OauthRefreshFamiliesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthrefreshfamily_user_id",
				Unique:  false,
				Columns: []*schema.Column{OauthRefreshFamiliesColumns[3]},
			},
		},
	}
	// OauthRefreshTokensColumns holds the columns for the "oauth_refresh_tokens" table.
	OauthRefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "client_id", Type: field.TypeString, Nullable: true},
		{Name: "family_id", Type: field.TypeString, Nullable: true},
		{Name: "generation", Type: field.TypeInt, Default: 0},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// OauthRefreshTokensTable holds the schema information for the "oauth_refresh_tokens" table.
	OauthRefreshTokensTable = &schema.Table{
		Name:       "oauth_refresh_tokens",
		Columns:    OauthRefreshTokensColumns,
		PrimaryKey: []*schema.Column{OauthRefreshTokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthrefreshtoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{OauthRefreshTokensColumns[3]},
			},
			{
				Name:    "oauthrefreshtoken_family_id",
				Unique:  false,
				Columns: []*schema.Column{OauthRefreshTokensColumns[5]},
			},
			{
				Name:    "oauthrefreshtoken_expires_at",
				Unique:  false,
				Columns: []*schema.Column{OauthRefreshTokensColumns[7]},
			},
		},
	}
	// OauthRevokedJtIsColumns holds the columns for the "oauth_revoked_jt_is" table.
	OauthRevokedJtIsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "jti", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// OauthRevokedJtIsTable holds the schema information for the "oauth_revoked_jt_is" table.
	OauthRevokedJtIsTable = &schema.Table{
		Name:       "oauth_revoked_jt_is",
		Columns:    OauthRevokedJtIsColumns,
		PrimaryKey: []*schema.Column{OauthRevokedJtIsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthrevokedjti_expires_at",
				Unique:  false,
				Columns: []*schema.Column{OauthRevokedJtIsColumns[3]},
			},
		},
	}
	// OauthTokenMetadataColumns holds the columns for the "oauth_token_metadata" table.
	OauthTokenMetadataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "token_id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "client_id", Type: field.TypeString},
		{Name: "issued_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "token_type", Type: field.TypeString},
		{Name: "audience", Type: field.TypeString, Nullable: true},
		{Name: "scopes", Type: field.TypeJSON},
		{Name: "family_id", Type: field.TypeString, Nullable: true},
		{Name: "jkt", Type: field.TypeString, Nullable: true},
		{Name: "extra_claims", Type: field.TypeJSON, Nullable: true},
	}
	// OauthTokenMetadataTable holds the schema information for the "oauth_token_metadata" table.
	OauthTokenMetadataTable = &schema.Table{
		Name:       "oauth_token_metadata",
		Columns:    OauthTokenMetadataColumns,
		PrimaryKey: []*schema.Column{OauthTokenMetadataColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthtokenmetadata_user_id",
				Unique:  false,
				Columns: []*schema.Column{OauthTokenMetadataColumns[3]},
			},
			{
				Name:    "oauthtokenmetadata_client_id",
				Unique:  false,
				Columns: []*schema.Column{OauthTokenMetadataColumns[4]},
			},
			{
				Name:    "oauthtokenmetadata_expires_at",
				Unique:  false,
				Columns: []*schema.Column{OauthTokenMetadataColumns[6]},
			},
			{
				Name:    "oauthtokenmetadata_user_id_client_id",
				Unique:  false,
				Columns: []*schema.Column{OauthTokenMetadataColumns[3], OauthTokenMetadataColumns[4]},
			},
		},
	}
	// OauthUserInfosColumns holds the columns for the "oauth_user_infos" table.
	OauthUserInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "info_json", Type: field.TypeString, Size: 2147483647},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OauthUserInfosTable holds the schema information for the "oauth_user_infos" table.
	OauthUserInfosTable = &schema.Table{
		Name:       "oauth_user_infos",
		Columns:    OauthUserInfosColumns,
		PrimaryKey: []*schema.Column{OauthUserInfosColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "oauthuserinfo_expires_at",
				Unique:  false,
				Columns: []*schema.Column{OauthUserInfosColumns[4]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "visibility", Type: field.TypeEnum, Enums: []string{"org", "private"}, Default: "private"},
		{Name: "archived", Type: field.TypeBool, Default: false},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_owner", Type: field.TypeUUID},
		{Name: "tenant_projects", Type: field.TypeUUID},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "projects_users_owner",
				Columns:    []*schema.Column{ProjectsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "projects_tenants_projects",
				Columns:    []*schema.Column{ProjectsColumns[8]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ProjectGroupSharesColumns holds the columns for the "project_group_shares" table.
	ProjectGroupSharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "group_name", Type: field.TypeString},
		{Name: "permission", Type: field.TypeEnum, Enums: []string{"read", "write"}},
		{Name: "project_group_shares", Type: field.TypeUUID},
		{Name: "project_group_share_created_by", Type: field.TypeUUID, Nullable: true},
	}
	// ProjectGroupSharesTable holds the schema information for the "project_group_shares" table.
	ProjectGroupSharesTable = &schema.Table{
		Name:       "project_group_shares",
		Columns:    ProjectGroupSharesColumns,
		PrimaryKey: []*schema.Column{ProjectGroupSharesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_group_shares_projects_group_shares",
				Columns:    []*schema.Column{ProjectGroupSharesColumns[4]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "project_group_shares_users_created_by",
				Columns:    []*schema.Column{ProjectGroupSharesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "projectgroupshare_group_name_project_group_shares",
				Unique:  true,
				Columns: []*schema.Column{ProjectGroupSharesColumns[2], ProjectGroupSharesColumns[4]},
			},
		},
	}
	// ProjectSharesColumns holds the columns for the "project_shares" table.
	ProjectSharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "permission", Type: field.TypeEnum, Enums: []string{"read", "write"}},
		{Name: "project_shares", Type: field.TypeUUID},
		{Name: "project_share_user", Type: field.TypeUUID},
		{Name: "project_share_created_by", Type: field.TypeUUID, Nullable: true},
	}
	// ProjectSharesTable holds the schema information for the "project_shares" table.
	ProjectSharesTable = &schema.Table{
		Name:       "project_shares",
		Columns:    ProjectSharesColumns,
		PrimaryKey: []*schema.Column{ProjectSharesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_shares_projects_shares",
				Columns:    []*schema.Column{ProjectSharesColumns[3]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "project_shares_users_user",
				Columns:    []*schema.Column{ProjectSharesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "project_shares_users_created_by",
				Columns:    []*schema.Column{ProjectSharesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "projectshare_project_shares_project_share_user",
				Unique:  true,
				Columns: []*schema.Column{ProjectSharesColumns[3], ProjectSharesColumns[4]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "external_subject", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "member"}, Default: "member"},
		{Name: "tenant_users", Type: field.TypeUUID},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_tenants_users",
				Columns:    []*schema.Column{UsersColumns[5]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DocumentsTable,
		DocumentSnapshotsTable,
		OauthAuthCodesTable,
		OauthAuthStatesTable,
		OauthClientsTable,
		OauthConsentsTable,
		OauthKeysTable,
		OauthProviderTokensTable,
		OauthRefreshFamiliesTable,
		OauthRefreshTokensTable,
		OauthRevokedJtIsTable,
		OauthTokenMetadataTable,
		OauthUserInfosTable,
		ProjectsTable,
		ProjectGroupSharesTable,
		ProjectSharesTable,
		TenantsTable,
		UsersTable,
	}
)

func init() {
	DocumentsTable.ForeignKeys[0].RefTable = UsersTable
	DocumentsTable.ForeignKeys[1].RefTable = UsersTable
	DocumentsTable.ForeignKeys[2].RefTable = ProjectsTable
	DocumentSnapshotsTable.ForeignKeys[0].RefTable = DocumentsTable
	DocumentSnapshotsTable.ForeignKeys[1].RefTable = UsersTable
	ProjectsTable.ForeignKeys[0].RefTable = UsersTable
	ProjectsTable.ForeignKeys[1].RefTable = TenantsTable
	ProjectGroupSharesTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectGroupSharesTable.ForeignKeys[1].RefTable = UsersTable
	ProjectSharesTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectSharesTable.ForeignKeys[1].RefTable = UsersTable
	ProjectSharesTable.ForeignKeys[2].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = TenantsTable
}
