// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/document"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/documentsnapshot"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/project"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/user"
	"github.com/google/uuid"
)

// DocumentCreate is the builder for creating a Document entity.
type DocumentCreate struct {
	config
	mutation *DocumentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentCreate) SetCreatedAt(v time.Time) *DocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableCreatedAt(v *time.Time) *DocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *DocumentCreate) SetTenantID(v uuid.UUID) *DocumentCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *DocumentCreate) SetTitle(v string) *DocumentCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetOverview sets the "overview" field.
func (_c *DocumentCreate) SetOverview(v string) *DocumentCreate {
	_c.mutation.SetOverview(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *DocumentCreate) SetBody(v string) *DocumentCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *DocumentCreate) SetContentType(v string) *DocumentCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableContentType(v *string) *DocumentCreate {
	if v != nil {
		_c.SetContentType(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *DocumentCreate) SetTags(v []string) *DocumentCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *DocumentCreate) SetVersion(v int) *DocumentCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableVersion(v *int) *DocumentCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetChangeComment sets the "change_comment" field.
func (_c *DocumentCreate) SetChangeComment(v string) *DocumentCreate {
	_c.mutation.SetChangeComment(v)
	return _c
}

// SetNillableChangeComment sets the "change_comment" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableChangeComment(v *string) *DocumentCreate {
	if v != nil {
		_c.SetChangeComment(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DocumentCreate) SetUpdatedAt(v time.Time) *DocumentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableUpdatedAt(v *time.Time) *DocumentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DocumentCreate) SetID(v uuid.UUID) *DocumentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DocumentCreate) SetNillableID(v *uuid.UUID) *DocumentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *DocumentCreate) SetProjectID(id uuid.UUID) *DocumentCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *DocumentCreate) SetProject(v *Project) *DocumentCreate {
	return _c.SetProjectID(v.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_c *DocumentCreate) SetCreatedByID(id uuid.UUID) *DocumentCreate {
	_c.mutation.SetCreatedByID(id)
	return _c
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (_c *DocumentCreate) SetNillableCreatedByID(id *uuid.UUID) *DocumentCreate {
	if id != nil {
		_c = _c.SetCreatedByID(*id)
	}
	return _c
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_c *DocumentCreate) SetCreatedBy(v *User) *DocumentCreate {
	return _c.SetCreatedByID(v.ID)
}

// SetUpdatedByID sets the "updated_by" edge to the User entity by ID.
func (_c *DocumentCreate) SetUpdatedByID(id uuid.UUID) *DocumentCreate {
	_c.mutation.SetUpdatedByID(id)
	return _c
}

// SetNillableUpdatedByID sets the "updated_by" edge to the User entity by ID if the given value is not nil.
func (_c *DocumentCreate) SetNillableUpdatedByID(id *uuid.UUID) *DocumentCreate {
	if id != nil {
		_c = _c.SetUpdatedByID(*id)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" edge to the User entity.
func (_c *DocumentCreate) SetUpdatedBy(v *User) *DocumentCreate {
	return _c.SetUpdatedByID(v.ID)
}

// AddSnapshotIDs adds the "snapshots" edge to the DocumentSnapshot entity by IDs.
func (_c *DocumentCreate) AddSnapshotIDs(ids ...uuid.UUID) *DocumentCreate {
	_c.mutation.AddSnapshotIDs(ids...)
	return _c
}

// AddSnapshots adds the "snapshots" edges to the DocumentSnapshot entity.
func (_c *DocumentCreate) AddSnapshots(v ...*DocumentSnapshot) *DocumentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSnapshotIDs(ids...)
}

// Mutation returns the DocumentMutation object of the builder.
func (_c *DocumentCreate) Mutation() *DocumentMutation {
	return _c.mutation
}

// Save creates the Document in the database.
func (_c *DocumentCreate) Save(ctx context.Context) (*Document, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentCreate) SaveX(ctx context.Context) *Document {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := document.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		v := document.DefaultContentType
		_c.mutation.SetContentType(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := document.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := document.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := document.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Document.created_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Document.tenant_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Document.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := document.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Document.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Overview(); !ok {
		return &ValidationError{Name: "overview", err: errors.New(`ent: missing required field "Document.overview"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Document.body"`)}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "Document.content_type"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Document.version"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Document.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Document.project"`)}
	}
	return nil
}

func (_c *DocumentCreate) sqlSave(ctx context.Context) (*Document, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentCreate) createSpec() (*Document, *sqlgraph.CreateSpec) {
	var (
		_node = &Document{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(document.Table, sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(document.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(document.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(document.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Overview(); ok {
		_spec.SetField(document.FieldOverview, field.TypeString, value)
		_node.Overview = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(document.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(document.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(document.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(document.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.ChangeComment(); ok {
		_spec.SetField(document.FieldChangeComment, field.TypeString, value)
		_node.ChangeComment = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(document.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   document.ProjectTable,
			Columns: []string{document.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_documents = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   document.CreatedByTable,
			Columns: []string{document.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.document_created_by = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UpdatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   document.UpdatedByTable,
			Columns: []string{document.UpdatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.document_updated_by = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   document.SnapshotsTable,
			Columns: []string{document.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documentsnapshot.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DocumentCreateBulk is the builder for creating many Document entities in bulk.
type DocumentCreateBulk struct {
	config
	err      error
	builders []*DocumentCreate
}

// Save creates the Document entities in the database.
func (_c *DocumentCreateBulk) Save(ctx context.Context) ([]*Document, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Document, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentCreateBulk) SaveX(ctx context.Context) []*Document {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
