// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/document"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/documentsnapshot"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/user"
	"github.com/google/uuid"
)

// DocumentSnapshotCreate is the builder for creating a DocumentSnapshot entity.
type DocumentSnapshotCreate struct {
	config
	mutation *DocumentSnapshotMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DocumentSnapshotCreate) SetCreatedAt(v time.Time) *DocumentSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DocumentSnapshotCreate) SetNillableCreatedAt(v *time.Time) *DocumentSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *DocumentSnapshotCreate) SetVersion(v int) *DocumentSnapshotCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetOverview sets the "overview" field.
func (_c *DocumentSnapshotCreate) SetOverview(v string) *DocumentSnapshotCreate {
	_c.mutation.SetOverview(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *DocumentSnapshotCreate) SetBody(v string) *DocumentSnapshotCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *DocumentSnapshotCreate) SetTags(v []string) *DocumentSnapshotCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *DocumentSnapshotCreate) SetComment(v string) *DocumentSnapshotCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *DocumentSnapshotCreate) SetNillableComment(v *string) *DocumentSnapshotCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DocumentSnapshotCreate) SetID(v uuid.UUID) *DocumentSnapshotCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DocumentSnapshotCreate) SetNillableID(v *uuid.UUID) *DocumentSnapshotCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDocumentID sets the "document" edge to the Document entity by ID.
func (_c *DocumentSnapshotCreate) SetDocumentID(id uuid.UUID) *DocumentSnapshotCreate {
	_c.mutation.SetDocumentID(id)
	return _c
}

// SetDocument sets the "document" edge to the Document entity.
func (_c *DocumentSnapshotCreate) SetDocument(v *Document) *DocumentSnapshotCreate {
	return _c.SetDocumentID(v.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_c *DocumentSnapshotCreate) SetCreatedByID(id uuid.UUID) *DocumentSnapshotCreate {
	_c.mutation.SetCreatedByID(id)
	return _c
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (_c *DocumentSnapshotCreate) SetNillableCreatedByID(id *uuid.UUID) *DocumentSnapshotCreate {
	if id != nil {
		_c = _c.SetCreatedByID(*id)
	}
	return _c
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_c *DocumentSnapshotCreate) SetCreatedBy(v *User) *DocumentSnapshotCreate {
	return _c.SetCreatedByID(v.ID)
}

// Mutation returns the DocumentSnapshotMutation object of the builder.
func (_c *DocumentSnapshotCreate) Mutation() *DocumentSnapshotMutation {
	return _c.mutation
}

// Save creates the DocumentSnapshot in the database.
func (_c *DocumentSnapshotCreate) Save(ctx context.Context) (*DocumentSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DocumentSnapshotCreate) SaveX(ctx context.Context) *DocumentSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DocumentSnapshotCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := documentsnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := documentsnapshot.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DocumentSnapshotCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DocumentSnapshot.created_at"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "DocumentSnapshot.version"`)}
	}
	if _, ok := _c.mutation.Overview(); !ok {
		return &ValidationError{Name: "overview", err: errors.New(`ent: missing required field "DocumentSnapshot.overview"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "DocumentSnapshot.body"`)}
	}
	if len(_c.mutation.DocumentIDs()) == 0 {
		return &ValidationError{Name: "document", err: errors.New(`ent: missing required edge "DocumentSnapshot.document"`)}
	}
	return nil
}

func (_c *DocumentSnapshotCreate) sqlSave(ctx context.Context) (*DocumentSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DocumentSnapshotCreate) createSpec() (*DocumentSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &DocumentSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(documentsnapshot.Table, sqlgraph.NewFieldSpec(documentsnapshot.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(documentsnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(documentsnapshot.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Overview(); ok {
		_spec.SetField(documentsnapshot.FieldOverview, field.TypeString, value)
		_node.Overview = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(documentsnapshot.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(documentsnapshot.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(documentsnapshot.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if nodes := _c.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   documentsnapshot.DocumentTable,
			Columns: []string{documentsnapshot.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.document_snapshots = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   documentsnapshot.CreatedByTable,
			Columns: []string{documentsnapshot.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.document_snapshot_created_by = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DocumentSnapshotCreateBulk is the builder for creating many DocumentSnapshot entities in bulk.
type DocumentSnapshotCreateBulk struct {
	config
	err      error
	builders []*DocumentSnapshotCreate
}

// Save creates the DocumentSnapshot entities in the database.
func (_c *DocumentSnapshotCreateBulk) Save(ctx context.Context) ([]*DocumentSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DocumentSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DocumentSnapshotCreateBulk) SaveX(ctx context.Context) []*DocumentSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DocumentSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DocumentSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
