// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthtokenmetadata"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/predicate"
)

// OAuthTokenMetadataUpdate is the builder for updating OAuthTokenMetadata entities.
type OAuthTokenMetadataUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthTokenMetadataMutation
}

// Where appends a list predicates to the OAuthTokenMetadataUpdate builder.
func (_u *OAuthTokenMetadataUpdate) Where(ps ...predicate.OAuthTokenMetadata) *OAuthTokenMetadataUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthTokenMetadataUpdate) SetUserID(v string) *OAuthTokenMetadataUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdate) SetNillableUserID(v *string) *OAuthTokenMetadataUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthTokenMetadataUpdate) SetClientID(v string) *OAuthTokenMetadataUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdate) SetNillableClientID(v *string) *OAuthTokenMetadataUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *OAuthTokenMetadataUpdate) SetIssuedAt(v time.Time) *OAuthTokenMetadataUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdate) SetNillableIssuedAt(v *time.Time) *OAuthTokenMetadataUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthTokenMetadataUpdate) SetExpiresAt(v time.Time) *OAuthTokenMetadataUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdate) SetNillableExpiresAt(v *time.Time) *OAuthTokenMetadataUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OAuthTokenMetadataUpdate) ClearExpiresAt() *OAuthTokenMetadataUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetTokenType sets the "token_type" field.
func (_u *OAuthTokenMetadataUpdate) SetTokenType(v string) *OAuthTokenMetadataUpdate {
	_u.mutation.SetTokenType(v)
	return _u
}

// SetNillableTokenType sets the "token_type" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdate) SetNillableTokenType(v *string) *OAuthTokenMetadataUpdate {
	if v != nil {
		_u.SetTokenType(*v)
	}
	return _u
}

// SetAudience sets the "audience" field.
func (_u *OAuthTokenMetadataUpdate) SetAudience(v string) *OAuthTokenMetadataUpdate {
	_u.mutation.SetAudience(v)
	return _u
}

// SetNillableAudience sets the "audience" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdate) SetNillableAudience(v *string) *OAuthTokenMetadataUpdate {
	if v != nil {
		_u.SetAudience(*v)
	}
	return _u
}

// ClearAudience clears the value of the "audience" field.
func (_u *OAuthTokenMetadataUpdate) ClearAudience() *OAuthTokenMetadataUpdate {
	_u.mutation.ClearAudience()
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthTokenMetadataUpdate) SetScopes(v []string) *OAuthTokenMetadataUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthTokenMetadataUpdate) AppendScopes(v []string) *OAuthTokenMetadataUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetFamilyID sets the "family_id" field.
func (_u *OAuthTokenMetadataUpdate) SetFamilyID(v string) *OAuthTokenMetadataUpdate {
	_u.mutation.SetFamilyID(v)
	return _u
}

// SetNillableFamilyID sets the "family_id" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdate) SetNillableFamilyID(v *string) *OAuthTokenMetadataUpdate {
	if v != nil {
		_u.SetFamilyID(*v)
	}
	return _u
}

// ClearFamilyID clears the value of the "family_id" field.
func (_u *OAuthTokenMetadataUpdate) ClearFamilyID() *OAuthTokenMetadataUpdate {
	_u.mutation.ClearFamilyID()
	return _u
}

// SetJkt sets the "jkt" field.
func (_u *OAuthTokenMetadataUpdate) SetJkt(v string) *OAuthTokenMetadataUpdate {
	_u.mutation.SetJkt(v)
	return _u
}

// SetNillableJkt sets the "jkt" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdate) SetNillableJkt(v *string) *OAuthTokenMetadataUpdate {
	if v != nil {
		_u.SetJkt(*v)
	}
	return _u
}

// ClearJkt clears the value of the "jkt" field.
func (_u *OAuthTokenMetadataUpdate) ClearJkt() *OAuthTokenMetadataUpdate {
	_u.mutation.ClearJkt()
	return _u
}

// SetExtraClaims sets the "extra_claims" field.
func (_u *OAuthTokenMetadataUpdate) SetExtraClaims(v map[string]interface{}) *OAuthTokenMetadataUpdate {
	_u.mutation.SetExtraClaims(v)
	return _u
}

// ClearExtraClaims clears the value of the "extra_claims" field.
func (_u *OAuthTokenMetadataUpdate) ClearExtraClaims() *OAuthTokenMetadataUpdate {
	_u.mutation.ClearExtraClaims()
	return _u
}

// Mutation returns the OAuthTokenMetadataMutation object of the builder.
func (_u *OAuthTokenMetadataUpdate) Mutation() *OAuthTokenMetadataMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthTokenMetadataUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthTokenMetadataUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthTokenMetadataUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthTokenMetadataUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthTokenMetadataUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := oauthtokenmetadata.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OAuthTokenMetadata.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthtokenmetadata.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthTokenMetadata.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenType(); ok {
		if err := oauthtokenmetadata.TokenTypeValidator(v); err != nil {
			return &ValidationError{Name: "token_type", err: fmt.Errorf(`ent: validator failed for field "OAuthTokenMetadata.token_type": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthTokenMetadataUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthtokenmetadata.Table, oauthtokenmetadata.Columns, sqlgraph.NewFieldSpec(oauthtokenmetadata.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthtokenmetadata.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthtokenmetadata.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(oauthtokenmetadata.FieldIssuedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthtokenmetadata.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthtokenmetadata.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TokenType(); ok {
		_spec.SetField(oauthtokenmetadata.FieldTokenType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Audience(); ok {
		_spec.SetField(oauthtokenmetadata.FieldAudience, field.TypeString, value)
	}
	if _u.mutation.AudienceCleared() {
		_spec.ClearField(oauthtokenmetadata.FieldAudience, field.TypeString)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthtokenmetadata.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthtokenmetadata.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.FamilyID(); ok {
		_spec.SetField(oauthtokenmetadata.FieldFamilyID, field.TypeString, value)
	}
	if _u.mutation.FamilyIDCleared() {
		_spec.ClearField(oauthtokenmetadata.FieldFamilyID, field.TypeString)
	}
	if value, ok := _u.mutation.Jkt(); ok {
		_spec.SetField(oauthtokenmetadata.FieldJkt, field.TypeString, value)
	}
	if _u.mutation.JktCleared() {
		_spec.ClearField(oauthtokenmetadata.FieldJkt, field.TypeString)
	}
	if value, ok := _u.mutation.ExtraClaims(); ok {
		_spec.SetField(oauthtokenmetadata.FieldExtraClaims, field.TypeJSON, value)
	}
	if _u.mutation.ExtraClaimsCleared() {
		_spec.ClearField(oauthtokenmetadata.FieldExtraClaims, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthtokenmetadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthTokenMetadataUpdateOne is the builder for updating a single OAuthTokenMetadata entity.
type OAuthTokenMetadataUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthTokenMetadataMutation
}

// SetUserID sets the "user_id" field.
func (_u *OAuthTokenMetadataUpdateOne) SetUserID(v string) *OAuthTokenMetadataUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdateOne) SetNillableUserID(v *string) *OAuthTokenMetadataUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthTokenMetadataUpdateOne) SetClientID(v string) *OAuthTokenMetadataUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdateOne) SetNillableClientID(v *string) *OAuthTokenMetadataUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *OAuthTokenMetadataUpdateOne) SetIssuedAt(v time.Time) *OAuthTokenMetadataUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdateOne) SetNillableIssuedAt(v *time.Time) *OAuthTokenMetadataUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthTokenMetadataUpdateOne) SetExpiresAt(v time.Time) *OAuthTokenMetadataUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthTokenMetadataUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *OAuthTokenMetadataUpdateOne) ClearExpiresAt() *OAuthTokenMetadataUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetTokenType sets the "token_type" field.
func (_u *OAuthTokenMetadataUpdateOne) SetTokenType(v string) *OAuthTokenMetadataUpdateOne {
	_u.mutation.SetTokenType(v)
	return _u
}

// SetNillableTokenType sets the "token_type" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdateOne) SetNillableTokenType(v *string) *OAuthTokenMetadataUpdateOne {
	if v != nil {
		_u.SetTokenType(*v)
	}
	return _u
}

// SetAudience sets the "audience" field.
func (_u *OAuthTokenMetadataUpdateOne) SetAudience(v string) *OAuthTokenMetadataUpdateOne {
	_u.mutation.SetAudience(v)
	return _u
}

// SetNillableAudience sets the "audience" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdateOne) SetNillableAudience(v *string) *OAuthTokenMetadataUpdateOne {
	if v != nil {
		_u.SetAudience(*v)
	}
	return _u
}

// ClearAudience clears the value of the "audience" field.
func (_u *OAuthTokenMetadataUpdateOne) ClearAudience() *OAuthTokenMetadataUpdateOne {
	_u.mutation.ClearAudience()
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthTokenMetadataUpdateOne) SetScopes(v []string) *OAuthTokenMetadataUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthTokenMetadataUpdateOne) AppendScopes(v []string) *OAuthTokenMetadataUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetFamilyID sets the "family_id" field.
func (_u *OAuthTokenMetadataUpdateOne) SetFamilyID(v string) *OAuthTokenMetadataUpdateOne {
	_u.mutation.SetFamilyID(v)
	return _u
}

// SetNillableFamilyID sets the "family_id" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdateOne) SetNillableFamilyID(v *string) *OAuthTokenMetadataUpdateOne {
	if v != nil {
		_u.SetFamilyID(*v)
	}
	return _u
}

// ClearFamilyID clears the value of the "family_id" field.
func (_u *OAuthTokenMetadataUpdateOne) ClearFamilyID() *OAuthTokenMetadataUpdateOne {
	_u.mutation.ClearFamilyID()
	return _u
}

// SetJkt sets the "jkt" field.
func (_u *OAuthTokenMetadataUpdateOne) SetJkt(v string) *OAuthTokenMetadataUpdateOne {
	_u.mutation.SetJkt(v)
	return _u
}

// SetNillableJkt sets the "jkt" field if the given value is not nil.
func (_u *OAuthTokenMetadataUpdateOne) SetNillableJkt(v *string) *OAuthTokenMetadataUpdateOne {
	if v != nil {
		_u.SetJkt(*v)
	}
	return _u
}

// ClearJkt clears the value of the "jkt" field.
func (_u *OAuthTokenMetadataUpdateOne) ClearJkt() *OAuthTokenMetadataUpdateOne {
	_u.mutation.ClearJkt()
	return _u
}

// SetExtraClaims sets the "extra_claims" field.
func (_u *OAuthTokenMetadataUpdateOne) SetExtraClaims(v map[string]interface{}) *OAuthTokenMetadataUpdateOne {
	_u.mutation.SetExtraClaims(v)
	return _u
}

// ClearExtraClaims clears the value of the "extra_claims" field.
func (_u *OAuthTokenMetadataUpdateOne) ClearExtraClaims() *OAuthTokenMetadataUpdateOne {
	_u.mutation.ClearExtraClaims()
	return _u
}

// Mutation returns the OAuthTokenMetadataMutation object of the builder.
func (_u *OAuthTokenMetadataUpdateOne) Mutation() *OAuthTokenMetadataMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthTokenMetadataUpdate builder.
func (_u *OAuthTokenMetadataUpdateOne) Where(ps ...predicate.OAuthTokenMetadata) *OAuthTokenMetadataUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthTokenMetadataUpdateOne) Select(field string, fields ...string) *OAuthTokenMetadataUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthTokenMetadata entity.
func (_u *OAuthTokenMetadataUpdateOne) Save(ctx context.Context) (*OAuthTokenMetadata, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthTokenMetadataUpdateOne) SaveX(ctx context.Context) *OAuthTokenMetadata {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthTokenMetadataUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthTokenMetadataUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthTokenMetadataUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := oauthtokenmetadata.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OAuthTokenMetadata.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthtokenmetadata.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthTokenMetadata.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenType(); ok {
		if err := oauthtokenmetadata.TokenTypeValidator(v); err != nil {
			return &ValidationError{Name: "token_type", err: fmt.Errorf(`ent: validator failed for field "OAuthTokenMetadata.token_type": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthTokenMetadataUpdateOne) sqlSave(ctx context.Context) (_node *OAuthTokenMetadata, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthtokenmetadata.Table, oauthtokenmetadata.Columns, sqlgraph.NewFieldSpec(oauthtokenmetadata.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthTokenMetadata.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthtokenmetadata.FieldID)
		for _, f := range fields {
			if !oauthtokenmetadata.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthtokenmetadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthtokenmetadata.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthtokenmetadata.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(oauthtokenmetadata.FieldIssuedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthtokenmetadata.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(oauthtokenmetadata.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TokenType(); ok {
		_spec.SetField(oauthtokenmetadata.FieldTokenType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Audience(); ok {
		_spec.SetField(oauthtokenmetadata.FieldAudience, field.TypeString, value)
	}
	if _u.mutation.AudienceCleared() {
		_spec.ClearField(oauthtokenmetadata.FieldAudience, field.TypeString)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthtokenmetadata.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthtokenmetadata.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.FamilyID(); ok {
		_spec.SetField(oauthtokenmetadata.FieldFamilyID, field.TypeString, value)
	}
	if _u.mutation.FamilyIDCleared() {
		_spec.ClearField(oauthtokenmetadata.FieldFamilyID, field.TypeString)
	}
	if value, ok := _u.mutation.Jkt(); ok {
		_spec.SetField(oauthtokenmetadata.FieldJkt, field.TypeString, value)
	}
	if _u.mutation.JktCleared() {
		_spec.ClearField(oauthtokenmetadata.FieldJkt, field.TypeString)
	}
	if value, ok := _u.mutation.ExtraClaims(); ok {
		_spec.SetField(oauthtokenmetadata.FieldExtraClaims, field.TypeJSON, value)
	}
	if _u.mutation.ExtraClaimsCleared() {
		_spec.ClearField(oauthtokenmetadata.FieldExtraClaims, field.TypeJSON)
	}
	_node = &OAuthTokenMetadata{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthtokenmetadata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
