// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthconsent"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/predicate"
)

// OAuthConsentUpdate is the builder for updating OAuthConsent entities.
type OAuthConsentUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthConsentMutation
}

// Where appends a list predicates to the OAuthConsentUpdate builder.
func (_u *OAuthConsentUpdate) Where(ps ...predicate.OAuthConsent) *OAuthConsentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthConsentUpdate) SetUserID(v string) *OAuthConsentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthConsentUpdate) SetNillableUserID(v *string) *OAuthConsentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthConsentUpdate) SetClientID(v string) *OAuthConsentUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthConsentUpdate) SetNillableClientID(v *string) *OAuthConsentUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *OAuthConsentUpdate) SetClientName(v string) *OAuthConsentUpdate {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *OAuthConsentUpdate) SetNillableClientName(v *string) *OAuthConsentUpdate {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// SetGrantedAt sets the "granted_at" field.
func (_u *OAuthConsentUpdate) SetGrantedAt(v time.Time) *OAuthConsentUpdate {
	_u.mutation.SetGrantedAt(v)
	return _u
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_u *OAuthConsentUpdate) SetNillableGrantedAt(v *time.Time) *OAuthConsentUpdate {
	if v != nil {
		_u.SetGrantedAt(*v)
	}
	return _u
}

// Mutation returns the OAuthConsentMutation object of the builder.
func (_u *OAuthConsentUpdate) Mutation() *OAuthConsentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthConsentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthConsentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthConsentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthConsentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthConsentUpdate) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthconsent.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthConsent.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientName(); ok {
		if err := oauthconsent.ClientNameValidator(v); err != nil {
			return &ValidationError{Name: "client_name", err: fmt.Errorf(`ent: validator failed for field "OAuthConsent.client_name": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthConsentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthconsent.Table, oauthconsent.Columns, sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthconsent.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthconsent.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(oauthconsent.FieldClientName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantedAt(); ok {
		_spec.SetField(oauthconsent.FieldGrantedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthconsent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthConsentUpdateOne is the builder for updating a single OAuthConsent entity.
type OAuthConsentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthConsentMutation
}

// SetUserID sets the "user_id" field.
func (_u *OAuthConsentUpdateOne) SetUserID(v string) *OAuthConsentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthConsentUpdateOne) SetNillableUserID(v *string) *OAuthConsentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthConsentUpdateOne) SetClientID(v string) *OAuthConsentUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthConsentUpdateOne) SetNillableClientID(v *string) *OAuthConsentUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *OAuthConsentUpdateOne) SetClientName(v string) *OAuthConsentUpdateOne {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *OAuthConsentUpdateOne) SetNillableClientName(v *string) *OAuthConsentUpdateOne {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// SetGrantedAt sets the "granted_at" field.
func (_u *OAuthConsentUpdateOne) SetGrantedAt(v time.Time) *OAuthConsentUpdateOne {
	_u.mutation.SetGrantedAt(v)
	return _u
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_u *OAuthConsentUpdateOne) SetNillableGrantedAt(v *time.Time) *OAuthConsentUpdateOne {
	if v != nil {
		_u.SetGrantedAt(*v)
	}
	return _u
}

// Mutation returns the OAuthConsentMutation object of the builder.
func (_u *OAuthConsentUpdateOne) Mutation() *OAuthConsentMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthConsentUpdate builder.
func (_u *OAuthConsentUpdateOne) Where(ps ...predicate.OAuthConsent) *OAuthConsentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthConsentUpdateOne) Select(field string, fields ...string) *OAuthConsentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthConsent entity.
func (_u *OAuthConsentUpdateOne) Save(ctx context.Context) (*OAuthConsent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthConsentUpdateOne) SaveX(ctx context.Context) *OAuthConsent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthConsentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthConsentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthConsentUpdateOne) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthconsent.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthConsent.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientName(); ok {
		if err := oauthconsent.ClientNameValidator(v); err != nil {
			return &ValidationError{Name: "client_name", err: fmt.Errorf(`ent: validator failed for field "OAuthConsent.client_name": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthConsentUpdateOne) sqlSave(ctx context.Context) (_node *OAuthConsent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthconsent.Table, oauthconsent.Columns, sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthConsent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthconsent.FieldID)
		for _, f := range fields {
			if !oauthconsent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthconsent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(oauthconsent.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthconsent.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(oauthconsent.FieldClientName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantedAt(); ok {
		_spec.SetField(oauthconsent.FieldGrantedAt, field.TypeTime, value)
	}
	_node = &OAuthConsent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthconsent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
