// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthkey"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/predicate"
)

// OAuthKeyUpdate is the builder for updating OAuthKey entities.
type OAuthKeyUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthKeyMutation
}

// Where appends a list predicates to the OAuthKeyUpdate builder.
func (_u *OAuthKeyUpdate) Where(ps ...predicate.OAuthKey) *OAuthKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSingleton sets the "singleton" field.
func (_u *OAuthKeyUpdate) SetSingleton(v int) *OAuthKeyUpdate {
	_u.mutation.ResetSingleton()
	_u.mutation.SetSingleton(v)
	return _u
}

// SetNillableSingleton sets the "singleton" field if the given value is not nil.
func (_u *OAuthKeyUpdate) SetNillableSingleton(v *int) *OAuthKeyUpdate {
	if v != nil {
		_u.SetSingleton(*v)
	}
	return _u
}

// AddSingleton adds value to the "singleton" field.
func (_u *OAuthKeyUpdate) AddSingleton(v int) *OAuthKeyUpdate {
	_u.mutation.AddSingleton(v)
	return _u
}

// Mutation returns the OAuthKeyMutation object of the builder.
func (_u *OAuthKeyUpdate) Mutation() *OAuthKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OAuthKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauthkey.Table, oauthkey.Columns, sqlgraph.NewFieldSpec(oauthkey.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Singleton(); ok {
		_spec.SetField(oauthkey.FieldSingleton, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSingleton(); ok {
		_spec.AddField(oauthkey.FieldSingleton, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthKeyUpdateOne is the builder for updating a single OAuthKey entity.
type OAuthKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthKeyMutation
}

// SetSingleton sets the "singleton" field.
func (_u *OAuthKeyUpdateOne) SetSingleton(v int) *OAuthKeyUpdateOne {
	_u.mutation.ResetSingleton()
	_u.mutation.SetSingleton(v)
	return _u
}

// SetNillableSingleton sets the "singleton" field if the given value is not nil.
func (_u *OAuthKeyUpdateOne) SetNillableSingleton(v *int) *OAuthKeyUpdateOne {
	if v != nil {
		_u.SetSingleton(*v)
	}
	return _u
}

// AddSingleton adds value to the "singleton" field.
func (_u *OAuthKeyUpdateOne) AddSingleton(v int) *OAuthKeyUpdateOne {
	_u.mutation.AddSingleton(v)
	return _u
}

// Mutation returns the OAuthKeyMutation object of the builder.
func (_u *OAuthKeyUpdateOne) Mutation() *OAuthKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthKeyUpdate builder.
func (_u *OAuthKeyUpdateOne) Where(ps ...predicate.OAuthKey) *OAuthKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthKeyUpdateOne) Select(field string, fields ...string) *OAuthKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthKey entity.
func (_u *OAuthKeyUpdateOne) Save(ctx context.Context) (*OAuthKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthKeyUpdateOne) SaveX(ctx context.Context) *OAuthKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OAuthKeyUpdateOne) sqlSave(ctx context.Context) (_node *OAuthKey, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauthkey.Table, oauthkey.Columns, sqlgraph.NewFieldSpec(oauthkey.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthkey.FieldID)
		for _, f := range fields {
			if !oauthkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Singleton(); ok {
		_spec.SetField(oauthkey.FieldSingleton, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSingleton(); ok {
		_spec.AddField(oauthkey.FieldSingleton, field.TypeInt, value)
	}
	_node = &OAuthKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
