// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthkey"
	"github.com/google/uuid"
)

// OAuthKeyCreate is the builder for creating a OAuthKey entity.
type OAuthKeyCreate struct {
	config
	mutation *OAuthKeyMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthKeyCreate) SetCreatedAt(v time.Time) *OAuthKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthKeyCreate) SetNillableCreatedAt(v *time.Time) *OAuthKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSingleton sets the "singleton" field.
func (_c *OAuthKeyCreate) SetSingleton(v int) *OAuthKeyCreate {
	_c.mutation.SetSingleton(v)
	return _c
}

// SetEcPrivateKeyPem sets the "ec_private_key_pem" field.
func (_c *OAuthKeyCreate) SetEcPrivateKeyPem(v string) *OAuthKeyCreate {
	_c.mutation.SetEcPrivateKeyPem(v)
	return _c
}

// SetKid sets the "kid" field.
func (_c *OAuthKeyCreate) SetKid(v string) *OAuthKeyCreate {
	_c.mutation.SetKid(v)
	return _c
}

// SetMasterSecret sets the "master_secret" field.
func (_c *OAuthKeyCreate) SetMasterSecret(v string) *OAuthKeyCreate {
	_c.mutation.SetMasterSecret(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthKeyCreate) SetID(v uuid.UUID) *OAuthKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthKeyCreate) SetNillableID(v *uuid.UUID) *OAuthKeyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OAuthKeyMutation object of the builder.
func (_c *OAuthKeyCreate) Mutation() *OAuthKeyMutation {
	return _c.mutation
}

// Save creates the OAuthKey in the database.
func (_c *OAuthKeyCreate) Save(ctx context.Context) (*OAuthKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthKeyCreate) SaveX(ctx context.Context) *OAuthKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthKeyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthkey.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthKeyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthKey.created_at"`)}
	}
	if _, ok := _c.mutation.Singleton(); !ok {
		return &ValidationError{Name: "singleton", err: errors.New(`ent: missing required field "OAuthKey.singleton"`)}
	}
	if _, ok := _c.mutation.EcPrivateKeyPem(); !ok {
		return &ValidationError{Name: "ec_private_key_pem", err: errors.New(`ent: missing required field "OAuthKey.ec_private_key_pem"`)}
	}
	if v, ok := _c.mutation.EcPrivateKeyPem(); ok {
		if err := oauthkey.EcPrivateKeyPemValidator(v); err != nil {
			return &ValidationError{Name: "ec_private_key_pem", err: fmt.Errorf(`ent: validator failed for field "OAuthKey.ec_private_key_pem": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kid(); !ok {
		return &ValidationError{Name: "kid", err: errors.New(`ent: missing required field "OAuthKey.kid"`)}
	}
	if v, ok := _c.mutation.Kid(); ok {
		if err := oauthkey.KidValidator(v); err != nil {
			return &ValidationError{Name: "kid", err: fmt.Errorf(`ent: validator failed for field "OAuthKey.kid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MasterSecret(); !ok {
		return &ValidationError{Name: "master_secret", err: errors.New(`ent: missing required field "OAuthKey.master_secret"`)}
	}
	if v, ok := _c.mutation.MasterSecret(); ok {
		if err := oauthkey.MasterSecretValidator(v); err != nil {
			return &ValidationError{Name: "master_secret", err: fmt.Errorf(`ent: validator failed for field "OAuthKey.master_secret": %w`, err)}
		}
	}
	return nil
}

func (_c *OAuthKeyCreate) sqlSave(ctx context.Context) (*OAuthKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthKeyCreate) createSpec() (*OAuthKey, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthkey.Table, sqlgraph.NewFieldSpec(oauthkey.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Singleton(); ok {
		_spec.SetField(oauthkey.FieldSingleton, field.TypeInt, value)
		_node.Singleton = value
	}
	if value, ok := _c.mutation.EcPrivateKeyPem(); ok {
		_spec.SetField(oauthkey.FieldEcPrivateKeyPem, field.TypeString, value)
		_node.EcPrivateKeyPem = value
	}
	if value, ok := _c.mutation.Kid(); ok {
		_spec.SetField(oauthkey.FieldKid, field.TypeString, value)
		_node.Kid = value
	}
	if value, ok := _c.mutation.MasterSecret(); ok {
		_spec.SetField(oauthkey.FieldMasterSecret, field.TypeString, value)
		_node.MasterSecret = value
	}
	return _node, _spec
}

// OAuthKeyCreateBulk is the builder for creating many OAuthKey entities in bulk.
type OAuthKeyCreateBulk struct {
	config
	err      error
	builders []*OAuthKeyCreate
}

// Save creates the OAuthKey entities in the database.
func (_c *OAuthKeyCreateBulk) Save(ctx context.Context) ([]*OAuthKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthKeyCreateBulk) SaveX(ctx context.Context) []*OAuthKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
