// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthtokenmetadata"
	"github.com/google/uuid"
)

// OAuthTokenMetadataCreate is the builder for creating a OAuthTokenMetadata entity.
type OAuthTokenMetadataCreate struct {
	config
	mutation *OAuthTokenMetadataMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthTokenMetadataCreate) SetCreatedAt(v time.Time) *OAuthTokenMetadataCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthTokenMetadataCreate) SetNillableCreatedAt(v *time.Time) *OAuthTokenMetadataCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTokenID sets the "token_id" field.
func (_c *OAuthTokenMetadataCreate) SetTokenID(v string) *OAuthTokenMetadataCreate {
	_c.mutation.SetTokenID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuthTokenMetadataCreate) SetUserID(v string) *OAuthTokenMetadataCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthTokenMetadataCreate) SetClientID(v string) *OAuthTokenMetadataCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *OAuthTokenMetadataCreate) SetIssuedAt(v time.Time) *OAuthTokenMetadataCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthTokenMetadataCreate) SetExpiresAt(v time.Time) *OAuthTokenMetadataCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *OAuthTokenMetadataCreate) SetNillableExpiresAt(v *time.Time) *OAuthTokenMetadataCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetTokenType sets the "token_type" field.
func (_c *OAuthTokenMetadataCreate) SetTokenType(v string) *OAuthTokenMetadataCreate {
	_c.mutation.SetTokenType(v)
	return _c
}

// SetAudience sets the "audience" field.
func (_c *OAuthTokenMetadataCreate) SetAudience(v string) *OAuthTokenMetadataCreate {
	_c.mutation.SetAudience(v)
	return _c
}

// SetNillableAudience sets the "audience" field if the given value is not nil.
func (_c *OAuthTokenMetadataCreate) SetNillableAudience(v *string) *OAuthTokenMetadataCreate {
	if v != nil {
		_c.SetAudience(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthTokenMetadataCreate) SetScopes(v []string) *OAuthTokenMetadataCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetFamilyID sets the "family_id" field.
func (_c *OAuthTokenMetadataCreate) SetFamilyID(v string) *OAuthTokenMetadataCreate {
	_c.mutation.SetFamilyID(v)
	return _c
}

// SetNillableFamilyID sets the "family_id" field if the given value is not nil.
func (_c *OAuthTokenMetadataCreate) SetNillableFamilyID(v *string) *OAuthTokenMetadataCreate {
	if v != nil {
		_c.SetFamilyID(*v)
	}
	return _c
}

// SetJkt sets the "jkt" field.
func (_c *OAuthTokenMetadataCreate) SetJkt(v string) *OAuthTokenMetadataCreate {
	_c.mutation.SetJkt(v)
	return _c
}

// SetNillableJkt sets the "jkt" field if the given value is not nil.
func (_c *OAuthTokenMetadataCreate) SetNillableJkt(v *string) *OAuthTokenMetadataCreate {
	if v != nil {
		_c.SetJkt(*v)
	}
	return _c
}

// SetExtraClaims sets the "extra_claims" field.
func (_c *OAuthTokenMetadataCreate) SetExtraClaims(v map[string]interface{}) *OAuthTokenMetadataCreate {
	_c.mutation.SetExtraClaims(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthTokenMetadataCreate) SetID(v uuid.UUID) *OAuthTokenMetadataCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthTokenMetadataCreate) SetNillableID(v *uuid.UUID) *OAuthTokenMetadataCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OAuthTokenMetadataMutation object of the builder.
func (_c *OAuthTokenMetadataCreate) Mutation() *OAuthTokenMetadataMutation {
	return _c.mutation
}

// Save creates the OAuthTokenMetadata in the database.
func (_c *OAuthTokenMetadataCreate) Save(ctx context.Context) (*OAuthTokenMetadata, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthTokenMetadataCreate) SaveX(ctx context.Context) *OAuthTokenMetadata {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthTokenMetadataCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthTokenMetadataCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthTokenMetadataCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthtokenmetadata.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthtokenmetadata.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthTokenMetadataCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthTokenMetadata.created_at"`)}
	}
	if _, ok := _c.mutation.TokenID(); !ok {
		return &ValidationError{Name: "token_id", err: errors.New(`ent: missing required field "OAuthTokenMetadata.token_id"`)}
	}
	if v, ok := _c.mutation.TokenID(); ok {
		if err := oauthtokenmetadata.TokenIDValidator(v); err != nil {
			return &ValidationError{Name: "token_id", err: fmt.Errorf(`ent: validator failed for field "OAuthTokenMetadata.token_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OAuthTokenMetadata.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := oauthtokenmetadata.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OAuthTokenMetadata.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthTokenMetadata.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthtokenmetadata.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthTokenMetadata.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IssuedAt(); !ok {
		return &ValidationError{Name: "issued_at", err: errors.New(`ent: missing required field "OAuthTokenMetadata.issued_at"`)}
	}
	if _, ok := _c.mutation.TokenType(); !ok {
		return &ValidationError{Name: "token_type", err: errors.New(`ent: missing required field "OAuthTokenMetadata.token_type"`)}
	}
	if v, ok := _c.mutation.TokenType(); ok {
		if err := oauthtokenmetadata.TokenTypeValidator(v); err != nil {
			return &ValidationError{Name: "token_type", err: fmt.Errorf(`ent: validator failed for field "OAuthTokenMetadata.token_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "OAuthTokenMetadata.scopes"`)}
	}
	return nil
}

func (_c *OAuthTokenMetadataCreate) sqlSave(ctx context.Context) (*OAuthTokenMetadata, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthTokenMetadataCreate) createSpec() (*OAuthTokenMetadata, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthTokenMetadata{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthtokenmetadata.Table, sqlgraph.NewFieldSpec(oauthtokenmetadata.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthtokenmetadata.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.TokenID(); ok {
		_spec.SetField(oauthtokenmetadata.FieldTokenID, field.TypeString, value)
		_node.TokenID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(oauthtokenmetadata.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthtokenmetadata.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(oauthtokenmetadata.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthtokenmetadata.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.TokenType(); ok {
		_spec.SetField(oauthtokenmetadata.FieldTokenType, field.TypeString, value)
		_node.TokenType = value
	}
	if value, ok := _c.mutation.Audience(); ok {
		_spec.SetField(oauthtokenmetadata.FieldAudience, field.TypeString, value)
		_node.Audience = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthtokenmetadata.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.FamilyID(); ok {
		_spec.SetField(oauthtokenmetadata.FieldFamilyID, field.TypeString, value)
		_node.FamilyID = value
	}
	if value, ok := _c.mutation.Jkt(); ok {
		_spec.SetField(oauthtokenmetadata.FieldJkt, field.TypeString, value)
		_node.Jkt = value
	}
	if value, ok := _c.mutation.ExtraClaims(); ok {
		_spec.SetField(oauthtokenmetadata.FieldExtraClaims, field.TypeJSON, value)
		_node.ExtraClaims = value
	}
	return _node, _spec
}

// OAuthTokenMetadataCreateBulk is the builder for creating many OAuthTokenMetadata entities in bulk.
type OAuthTokenMetadataCreateBulk struct {
	config
	err      error
	builders []*OAuthTokenMetadataCreate
}

// Save creates the OAuthTokenMetadata entities in the database.
func (_c *OAuthTokenMetadataCreateBulk) Save(ctx context.Context) ([]*OAuthTokenMetadata, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthTokenMetadata, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthTokenMetadataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthTokenMetadataCreateBulk) SaveX(ctx context.Context) []*OAuthTokenMetadata {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthTokenMetadataCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthTokenMetadataCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
