// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthrevokedjti"
	"github.com/google/uuid"
)

// OAuthRevokedJTICreate is the builder for creating a OAuthRevokedJTI entity.
type OAuthRevokedJTICreate struct {
	config
	mutation *OAuthRevokedJTIMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthRevokedJTICreate) SetCreatedAt(v time.Time) *OAuthRevokedJTICreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthRevokedJTICreate) SetNillableCreatedAt(v *time.Time) *OAuthRevokedJTICreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetJti sets the "jti" field.
func (_c *OAuthRevokedJTICreate) SetJti(v string) *OAuthRevokedJTICreate {
	_c.mutation.SetJti(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthRevokedJTICreate) SetExpiresAt(v time.Time) *OAuthRevokedJTICreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthRevokedJTICreate) SetID(v uuid.UUID) *OAuthRevokedJTICreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthRevokedJTICreate) SetNillableID(v *uuid.UUID) *OAuthRevokedJTICreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OAuthRevokedJTIMutation object of the builder.
func (_c *OAuthRevokedJTICreate) Mutation() *OAuthRevokedJTIMutation {
	return _c.mutation
}

// Save creates the OAuthRevokedJTI in the database.
func (_c *OAuthRevokedJTICreate) Save(ctx context.Context) (*OAuthRevokedJTI, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthRevokedJTICreate) SaveX(ctx context.Context) *OAuthRevokedJTI {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthRevokedJTICreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthRevokedJTICreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthRevokedJTICreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthrevokedjti.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthrevokedjti.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthRevokedJTICreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthRevokedJTI.created_at"`)}
	}
	if _, ok := _c.mutation.Jti(); !ok {
		return &ValidationError{Name: "jti", err: errors.New(`ent: missing required field "OAuthRevokedJTI.jti"`)}
	}
	if v, ok := _c.mutation.Jti(); ok {
		if err := oauthrevokedjti.JtiValidator(v); err != nil {
			return &ValidationError{Name: "jti", err: fmt.Errorf(`ent: validator failed for field "OAuthRevokedJTI.jti": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthRevokedJTI.expires_at"`)}
	}
	return nil
}

func (_c *OAuthRevokedJTICreate) sqlSave(ctx context.Context) (*OAuthRevokedJTI, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthRevokedJTICreate) createSpec() (*OAuthRevokedJTI, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthRevokedJTI{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthrevokedjti.Table, sqlgraph.NewFieldSpec(oauthrevokedjti.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthrevokedjti.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Jti(); ok {
		_spec.SetField(oauthrevokedjti.FieldJti, field.TypeString, value)
		_node.Jti = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthrevokedjti.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OAuthRevokedJTICreateBulk is the builder for creating many OAuthRevokedJTI entities in bulk.
type OAuthRevokedJTICreateBulk struct {
	config
	err      error
	builders []*OAuthRevokedJTICreate
}

// Save creates the OAuthRevokedJTI entities in the database.
func (_c *OAuthRevokedJTICreateBulk) Save(ctx context.Context) ([]*OAuthRevokedJTI, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthRevokedJTI, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthRevokedJTIMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthRevokedJTICreateBulk) SaveX(ctx context.Context) []*OAuthRevokedJTI {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthRevokedJTICreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthRevokedJTICreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
