// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthclient"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/predicate"
)

// OAuthClientUpdate is the builder for updating OAuthClient entities.
type OAuthClientUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthClientMutation
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (_u *OAuthClientUpdate) Where(ps ...predicate.OAuthClient) *OAuthClientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *OAuthClientUpdate) SetClientSecretHash(v string) *OAuthClientUpdate {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableClientSecretHash(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetClientSecretHash(*v)
	}
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *OAuthClientUpdate) SetClientType(v string) *OAuthClientUpdate {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableClientType(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// SetRedirectUris sets the "redirect_uris" field.
func (_u *OAuthClientUpdate) SetRedirectUris(v []string) *OAuthClientUpdate {
	_u.mutation.SetRedirectUris(v)
	return _u
}

// AppendRedirectUris appends value to the "redirect_uris" field.
func (_u *OAuthClientUpdate) AppendRedirectUris(v []string) *OAuthClientUpdate {
	_u.mutation.AppendRedirectUris(v)
	return _u
}

// SetTokenEndpointAuthMethod sets the "token_endpoint_auth_method" field.
func (_u *OAuthClientUpdate) SetTokenEndpointAuthMethod(v string) *OAuthClientUpdate {
	_u.mutation.SetTokenEndpointAuthMethod(v)
	return _u
}

// SetNillableTokenEndpointAuthMethod sets the "token_endpoint_auth_method" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableTokenEndpointAuthMethod(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetTokenEndpointAuthMethod(*v)
	}
	return _u
}

// SetGrantTypes sets the "grant_types" field.
func (_u *OAuthClientUpdate) SetGrantTypes(v []string) *OAuthClientUpdate {
	_u.mutation.SetGrantTypes(v)
	return _u
}

// AppendGrantTypes appends value to the "grant_types" field.
func (_u *OAuthClientUpdate) AppendGrantTypes(v []string) *OAuthClientUpdate {
	_u.mutation.AppendGrantTypes(v)
	return _u
}

// SetResponseTypes sets the "response_types" field.
func (_u *OAuthClientUpdate) SetResponseTypes(v []string) *OAuthClientUpdate {
	_u.mutation.SetResponseTypes(v)
	return _u
}

// AppendResponseTypes appends value to the "response_types" field.
func (_u *OAuthClientUpdate) AppendResponseTypes(v []string) *OAuthClientUpdate {
	_u.mutation.AppendResponseTypes(v)
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *OAuthClientUpdate) SetClientName(v string) *OAuthClientUpdate {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableClientName(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthClientUpdate) SetScopes(v []string) *OAuthClientUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthClientUpdate) AppendScopes(v []string) *OAuthClientUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetRegistrationAccessTokenHash sets the "registration_access_token_hash" field.
func (_u *OAuthClientUpdate) SetRegistrationAccessTokenHash(v string) *OAuthClientUpdate {
	_u.mutation.SetRegistrationAccessTokenHash(v)
	return _u
}

// SetNillableRegistrationAccessTokenHash sets the "registration_access_token_hash" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableRegistrationAccessTokenHash(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetRegistrationAccessTokenHash(*v)
	}
	return _u
}

// ClearRegistrationAccessTokenHash clears the value of the "registration_access_token_hash" field.
func (_u *OAuthClientUpdate) ClearRegistrationAccessTokenHash() *OAuthClientUpdate {
	_u.mutation.ClearRegistrationAccessTokenHash()
	return _u
}

// SetRegistrationIP sets the "registration_ip" field.
func (_u *OAuthClientUpdate) SetRegistrationIP(v string) *OAuthClientUpdate {
	_u.mutation.SetRegistrationIP(v)
	return _u
}

// SetNillableRegistrationIP sets the "registration_ip" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableRegistrationIP(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetRegistrationIP(*v)
	}
	return _u
}

// ClearRegistrationIP clears the value of the "registration_ip" field.
func (_u *OAuthClientUpdate) ClearRegistrationIP() *OAuthClientUpdate {
	_u.mutation.ClearRegistrationIP()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthClientUpdate) SetUpdatedAt(v time.Time) *OAuthClientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_u *OAuthClientUpdate) Mutation() *OAuthClientMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthClientUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthClientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthClientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthClientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthClientUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthClientUpdate) check() error {
	if v, ok := _u.mutation.ClientType(); ok {
		if err := oauthclient.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenEndpointAuthMethod(); ok {
		if err := oauthclient.TokenEndpointAuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "token_endpoint_auth_method", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.token_endpoint_auth_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientName(); ok {
		if err := oauthclient.ClientNameValidator(v); err != nil {
			return &ValidationError{Name: "client_name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_name": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthClientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(oauthclient.FieldClientSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(oauthclient.FieldClientType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldRedirectUris, value)
		})
	}
	if value, ok := _u.mutation.TokenEndpointAuthMethod(); ok {
		_spec.SetField(oauthclient.FieldTokenEndpointAuthMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantTypes(); ok {
		_spec.SetField(oauthclient.FieldGrantTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGrantTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldGrantTypes, value)
		})
	}
	if value, ok := _u.mutation.ResponseTypes(); ok {
		_spec.SetField(oauthclient.FieldResponseTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldResponseTypes, value)
		})
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(oauthclient.FieldClientName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthclient.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.RegistrationAccessTokenHash(); ok {
		_spec.SetField(oauthclient.FieldRegistrationAccessTokenHash, field.TypeString, value)
	}
	if _u.mutation.RegistrationAccessTokenHashCleared() {
		_spec.ClearField(oauthclient.FieldRegistrationAccessTokenHash, field.TypeString)
	}
	if value, ok := _u.mutation.RegistrationIP(); ok {
		_spec.SetField(oauthclient.FieldRegistrationIP, field.TypeString, value)
	}
	if _u.mutation.RegistrationIPCleared() {
		_spec.ClearField(oauthclient.FieldRegistrationIP, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthClientUpdateOne is the builder for updating a single OAuthClient entity.
type OAuthClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthClientMutation
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *OAuthClientUpdateOne) SetClientSecretHash(v string) *OAuthClientUpdateOne {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableClientSecretHash(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetClientSecretHash(*v)
	}
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *OAuthClientUpdateOne) SetClientType(v string) *OAuthClientUpdateOne {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableClientType(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// SetRedirectUris sets the "redirect_uris" field.
func (_u *OAuthClientUpdateOne) SetRedirectUris(v []string) *OAuthClientUpdateOne {
	_u.mutation.SetRedirectUris(v)
	return _u
}

// AppendRedirectUris appends value to the "redirect_uris" field.
func (_u *OAuthClientUpdateOne) AppendRedirectUris(v []string) *OAuthClientUpdateOne {
	_u.mutation.AppendRedirectUris(v)
	return _u
}

// SetTokenEndpointAuthMethod sets the "token_endpoint_auth_method" field.
func (_u *OAuthClientUpdateOne) SetTokenEndpointAuthMethod(v string) *OAuthClientUpdateOne {
	_u.mutation.SetTokenEndpointAuthMethod(v)
	return _u
}

// SetNillableTokenEndpointAuthMethod sets the "token_endpoint_auth_method" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableTokenEndpointAuthMethod(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetTokenEndpointAuthMethod(*v)
	}
	return _u
}

// SetGrantTypes sets the "grant_types" field.
func (_u *OAuthClientUpdateOne) SetGrantTypes(v []string) *OAuthClientUpdateOne {
	_u.mutation.SetGrantTypes(v)
	return _u
}

// AppendGrantTypes appends value to the "grant_types" field.
func (_u *OAuthClientUpdateOne) AppendGrantTypes(v []string) *OAuthClientUpdateOne {
	_u.mutation.AppendGrantTypes(v)
	return _u
}

// SetResponseTypes sets the "response_types" field.
func (_u *OAuthClientUpdateOne) SetResponseTypes(v []string) *OAuthClientUpdateOne {
	_u.mutation.SetResponseTypes(v)
	return _u
}

// AppendResponseTypes appends value to the "response_types" field.
func (_u *OAuthClientUpdateOne) AppendResponseTypes(v []string) *OAuthClientUpdateOne {
	_u.mutation.AppendResponseTypes(v)
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *OAuthClientUpdateOne) SetClientName(v string) *OAuthClientUpdateOne {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableClientName(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthClientUpdateOne) SetScopes(v []string) *OAuthClientUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthClientUpdateOne) AppendScopes(v []string) *OAuthClientUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetRegistrationAccessTokenHash sets the "registration_access_token_hash" field.
func (_u *OAuthClientUpdateOne) SetRegistrationAccessTokenHash(v string) *OAuthClientUpdateOne {
	_u.mutation.SetRegistrationAccessTokenHash(v)
	return _u
}

// SetNillableRegistrationAccessTokenHash sets the "registration_access_token_hash" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableRegistrationAccessTokenHash(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetRegistrationAccessTokenHash(*v)
	}
	return _u
}

// ClearRegistrationAccessTokenHash clears the value of the "registration_access_token_hash" field.
func (_u *OAuthClientUpdateOne) ClearRegistrationAccessTokenHash() *OAuthClientUpdateOne {
	_u.mutation.ClearRegistrationAccessTokenHash()
	return _u
}

// SetRegistrationIP sets the "registration_ip" field.
func (_u *OAuthClientUpdateOne) SetRegistrationIP(v string) *OAuthClientUpdateOne {
	_u.mutation.SetRegistrationIP(v)
	return _u
}

// SetNillableRegistrationIP sets the "registration_ip" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableRegistrationIP(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetRegistrationIP(*v)
	}
	return _u
}

// ClearRegistrationIP clears the value of the "registration_ip" field.
func (_u *OAuthClientUpdateOne) ClearRegistrationIP() *OAuthClientUpdateOne {
	_u.mutation.ClearRegistrationIP()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthClientUpdateOne) SetUpdatedAt(v time.Time) *OAuthClientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_u *OAuthClientUpdateOne) Mutation() *OAuthClientMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (_u *OAuthClientUpdateOne) Where(ps ...predicate.OAuthClient) *OAuthClientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthClientUpdateOne) Select(field string, fields ...string) *OAuthClientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthClient entity.
func (_u *OAuthClientUpdateOne) Save(ctx context.Context) (*OAuthClient, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthClientUpdateOne) SaveX(ctx context.Context) *OAuthClient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthClientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthClientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthClientUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthClientUpdateOne) check() error {
	if v, ok := _u.mutation.ClientType(); ok {
		if err := oauthclient.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenEndpointAuthMethod(); ok {
		if err := oauthclient.TokenEndpointAuthMethodValidator(v); err != nil {
			return &ValidationError{Name: "token_endpoint_auth_method", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.token_endpoint_auth_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientName(); ok {
		if err := oauthclient.ClientNameValidator(v); err != nil {
			return &ValidationError{Name: "client_name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_name": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthClientUpdateOne) sqlSave(ctx context.Context) (_node *OAuthClient, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthClient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthclient.FieldID)
		for _, f := range fields {
			if !oauthclient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(oauthclient.FieldClientSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(oauthclient.FieldClientType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldRedirectUris, value)
		})
	}
	if value, ok := _u.mutation.TokenEndpointAuthMethod(); ok {
		_spec.SetField(oauthclient.FieldTokenEndpointAuthMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantTypes(); ok {
		_spec.SetField(oauthclient.FieldGrantTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGrantTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldGrantTypes, value)
		})
	}
	if value, ok := _u.mutation.ResponseTypes(); ok {
		_spec.SetField(oauthclient.FieldResponseTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResponseTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldResponseTypes, value)
		})
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(oauthclient.FieldClientName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthclient.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.RegistrationAccessTokenHash(); ok {
		_spec.SetField(oauthclient.FieldRegistrationAccessTokenHash, field.TypeString, value)
	}
	if _u.mutation.RegistrationAccessTokenHashCleared() {
		_spec.ClearField(oauthclient.FieldRegistrationAccessTokenHash, field.TypeString)
	}
	if value, ok := _u.mutation.RegistrationIP(); ok {
		_spec.SetField(oauthclient.FieldRegistrationIP, field.TypeString, value)
	}
	if _u.mutation.RegistrationIPCleared() {
		_spec.ClearField(oauthclient.FieldRegistrationIP, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OAuthClient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
