// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/predicate"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/project"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/projectshare"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/user"
	"github.com/google/uuid"
)

// ProjectShareUpdate is the builder for updating ProjectShare entities.
type ProjectShareUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectShareMutation
}

// Where appends a list predicates to the ProjectShareUpdate builder.
func (_u *ProjectShareUpdate) Where(ps ...predicate.ProjectShare) *ProjectShareUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPermission sets the "permission" field.
func (_u *ProjectShareUpdate) SetPermission(v projectshare.Permission) *ProjectShareUpdate {
	_u.mutation.SetPermission(v)
	return _u
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_u *ProjectShareUpdate) SetNillablePermission(v *projectshare.Permission) *ProjectShareUpdate {
	if v != nil {
		_u.SetPermission(*v)
	}
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ProjectShareUpdate) SetProjectID(id uuid.UUID) *ProjectShareUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectShareUpdate) SetProject(v *Project) *ProjectShareUpdate {
	return _u.SetProjectID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ProjectShareUpdate) SetUserID(id uuid.UUID) *ProjectShareUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProjectShareUpdate) SetUser(v *User) *ProjectShareUpdate {
	return _u.SetUserID(v.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_u *ProjectShareUpdate) SetCreatedByID(id uuid.UUID) *ProjectShareUpdate {
	_u.mutation.SetCreatedByID(id)
	return _u
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (_u *ProjectShareUpdate) SetNillableCreatedByID(id *uuid.UUID) *ProjectShareUpdate {
	if id != nil {
		_u = _u.SetCreatedByID(*id)
	}
	return _u
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *ProjectShareUpdate) SetCreatedBy(v *User) *ProjectShareUpdate {
	return _u.SetCreatedByID(v.ID)
}

// Mutation returns the ProjectShareMutation object of the builder.
func (_u *ProjectShareUpdate) Mutation() *ProjectShareMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectShareUpdate) ClearProject() *ProjectShareUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProjectShareUpdate) ClearUser() *ProjectShareUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *ProjectShareUpdate) ClearCreatedBy() *ProjectShareUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectShareUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectShareUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectShareUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectShareUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectShareUpdate) check() error {
	if v, ok := _u.mutation.Permission(); ok {
		if err := projectshare.PermissionValidator(v); err != nil {
			return &ValidationError{Name: "permission", err: fmt.Errorf(`ent: validator failed for field "ProjectShare.permission": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectShare.project"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectShare.user"`)
	}
	return nil
}

func (_u *ProjectShareUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectshare.Table, projectshare.Columns, sqlgraph.NewFieldSpec(projectshare.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Permission(); ok {
		_spec.SetField(projectshare.FieldPermission, field.TypeEnum, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectshare.ProjectTable,
			Columns: []string{projectshare.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectshare.ProjectTable,
			Columns: []string{projectshare.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectshare.UserTable,
			Columns: []string{projectshare.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectshare.UserTable,
			Columns: []string{projectshare.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectshare.CreatedByTable,
			Columns: []string{projectshare.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectshare.CreatedByTable,
			Columns: []string{projectshare.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectshare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectShareUpdateOne is the builder for updating a single ProjectShare entity.
type ProjectShareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectShareMutation
}

// SetPermission sets the "permission" field.
func (_u *ProjectShareUpdateOne) SetPermission(v projectshare.Permission) *ProjectShareUpdateOne {
	_u.mutation.SetPermission(v)
	return _u
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_u *ProjectShareUpdateOne) SetNillablePermission(v *projectshare.Permission) *ProjectShareUpdateOne {
	if v != nil {
		_u.SetPermission(*v)
	}
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ProjectShareUpdateOne) SetProjectID(id uuid.UUID) *ProjectShareUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectShareUpdateOne) SetProject(v *Project) *ProjectShareUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ProjectShareUpdateOne) SetUserID(id uuid.UUID) *ProjectShareUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProjectShareUpdateOne) SetUser(v *User) *ProjectShareUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetCreatedByID sets the "created_by" edge to the User entity by ID.
func (_u *ProjectShareUpdateOne) SetCreatedByID(id uuid.UUID) *ProjectShareUpdateOne {
	_u.mutation.SetCreatedByID(id)
	return _u
}

// SetNillableCreatedByID sets the "created_by" edge to the User entity by ID if the given value is not nil.
func (_u *ProjectShareUpdateOne) SetNillableCreatedByID(id *uuid.UUID) *ProjectShareUpdateOne {
	if id != nil {
		_u = _u.SetCreatedByID(*id)
	}
	return _u
}

// SetCreatedBy sets the "created_by" edge to the User entity.
func (_u *ProjectShareUpdateOne) SetCreatedBy(v *User) *ProjectShareUpdateOne {
	return _u.SetCreatedByID(v.ID)
}

// Mutation returns the ProjectShareMutation object of the builder.
func (_u *ProjectShareUpdateOne) Mutation() *ProjectShareMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectShareUpdateOne) ClearProject() *ProjectShareUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProjectShareUpdateOne) ClearUser() *ProjectShareUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearCreatedBy clears the "created_by" edge to the User entity.
func (_u *ProjectShareUpdateOne) ClearCreatedBy() *ProjectShareUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Where appends a list predicates to the ProjectShareUpdate builder.
func (_u *ProjectShareUpdateOne) Where(ps ...predicate.ProjectShare) *ProjectShareUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectShareUpdateOne) Select(field string, fields ...string) *ProjectShareUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectShare entity.
func (_u *ProjectShareUpdateOne) Save(ctx context.Context) (*ProjectShare, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectShareUpdateOne) SaveX(ctx context.Context) *ProjectShare {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectShareUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectShareUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectShareUpdateOne) check() error {
	if v, ok := _u.mutation.Permission(); ok {
		if err := projectshare.PermissionValidator(v); err != nil {
			return &ValidationError{Name: "permission", err: fmt.Errorf(`ent: validator failed for field "ProjectShare.permission": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectShare.project"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectShare.user"`)
	}
	return nil
}

func (_u *ProjectShareUpdateOne) sqlSave(ctx context.Context) (_node *ProjectShare, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectshare.Table, projectshare.Columns, sqlgraph.NewFieldSpec(projectshare.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectShare.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectshare.FieldID)
		for _, f := range fields {
			if !projectshare.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Permission(); ok {
		_spec.SetField(projectshare.FieldPermission, field.TypeEnum, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectshare.ProjectTable,
			Columns: []string{projectshare.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectshare.ProjectTable,
			Columns: []string{projectshare.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectshare.UserTable,
			Columns: []string{projectshare.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectshare.UserTable,
			Columns: []string{projectshare.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectshare.CreatedByTable,
			Columns: []string{projectshare.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectshare.CreatedByTable,
			Columns: []string{projectshare.CreatedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectShare{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectshare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
