// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/project"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/projectgroupshare"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/user"
	"github.com/google/uuid"
)

// ProjectGroupShare is the model entity for the ProjectGroupShare schema.
type ProjectGroupShare struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// GroupName holds the value of the "group_name" field.
	GroupName string `json:"group_name,omitempty"`
	// Permission holds the value of the "permission" field.
	Permission projectgroupshare.Permission `json:"permission,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectGroupShareQuery when eager-loading is set.
	Edges                          ProjectGroupShareEdges `json:"edges"`
	project_group_shares           *uuid.UUID
	project_group_share_created_by *uuid.UUID
	selectValues                   sql.SelectValues
}

// ProjectGroupShareEdges holds the relations/edges for other nodes in the graph.
type ProjectGroupShareEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectGroupShareEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectGroupShareEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectGroupShare) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectgroupshare.FieldGroupName, projectgroupshare.FieldPermission:
			values[i] = new(sql.NullString)
		case projectgroupshare.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case projectgroupshare.FieldID:
			values[i] = new(uuid.UUID)
		case projectgroupshare.ForeignKeys[0]: // project_group_shares
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case projectgroupshare.ForeignKeys[1]: // project_group_share_created_by
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectGroupShare fields.
func (_m *ProjectGroupShare) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectgroupshare.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case projectgroupshare.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case projectgroupshare.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				_m.GroupName = value.String
			}
		case projectgroupshare.FieldPermission:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission", values[i])
			} else if value.Valid {
				_m.Permission = projectgroupshare.Permission(value.String)
			}
		case projectgroupshare.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field project_group_shares", values[i])
			} else if value.Valid {
				_m.project_group_shares = new(uuid.UUID)
				*_m.project_group_shares = *value.S.(*uuid.UUID)
			}
		case projectgroupshare.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field project_group_share_created_by", values[i])
			} else if value.Valid {
				_m.project_group_share_created_by = new(uuid.UUID)
				*_m.project_group_share_created_by = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectGroupShare.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectGroupShare) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectGroupShare entity.
func (_m *ProjectGroupShare) QueryProject() *ProjectQuery {
	return NewProjectGroupShareClient(_m.config).QueryProject(_m)
}

// QueryCreatedBy queries the "created_by" edge of the ProjectGroupShare entity.
func (_m *ProjectGroupShare) QueryCreatedBy() *UserQuery {
	return NewProjectGroupShareClient(_m.config).QueryCreatedBy(_m)
}

// Update returns a builder for updating this ProjectGroupShare.
// Note that you need to call ProjectGroupShare.Unwrap() before calling this method if this ProjectGroupShare
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectGroupShare) Update() *ProjectGroupShareUpdateOne {
	return NewProjectGroupShareClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectGroupShare entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectGroupShare) Unwrap() *ProjectGroupShare {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectGroupShare is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectGroupShare) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectGroupShare(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_name=")
	builder.WriteString(_m.GroupName)
	builder.WriteString(", ")
	builder.WriteString("permission=")
	builder.WriteString(fmt.Sprintf("%v", _m.Permission))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectGroupShares is a parsable slice of ProjectGroupShare.
type ProjectGroupShares []*ProjectGroupShare
