// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Fishwaldo/mcp-docstore/internal/ent/document"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/documentsnapshot"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthauthcode"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthauthstate"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthclient"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthprovidertoken"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthrefreshfamily"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthrefreshtoken"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthrevokedjti"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthtokenmetadata"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/oauthuserinfo"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/project"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/projectgroupshare"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/projectshare"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/schema"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/session"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/tenant"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	documentMixin := schema.Document{}.Mixin()
	documentMixinFields0 := documentMixin[0].Fields()
	_ = documentMixinFields0
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescCreatedAt is the schema descriptor for created_at field.
	documentDescCreatedAt := documentMixinFields0[1].Descriptor()
	// document.DefaultCreatedAt holds the default value on creation for the created_at field.
	document.DefaultCreatedAt = documentDescCreatedAt.Default.(func() time.Time)
	// documentDescTitle is the schema descriptor for title field.
	documentDescTitle := documentFields[1].Descriptor()
	// document.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	document.TitleValidator = documentDescTitle.Validators[0].(func(string) error)
	// documentDescContentType is the schema descriptor for content_type field.
	documentDescContentType := documentFields[4].Descriptor()
	// document.DefaultContentType holds the default value on creation for the content_type field.
	document.DefaultContentType = documentDescContentType.Default.(string)
	// documentDescVersion is the schema descriptor for version field.
	documentDescVersion := documentFields[6].Descriptor()
	// document.DefaultVersion holds the default value on creation for the version field.
	document.DefaultVersion = documentDescVersion.Default.(int)
	// documentDescUpdatedAt is the schema descriptor for updated_at field.
	documentDescUpdatedAt := documentFields[8].Descriptor()
	// document.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	document.DefaultUpdatedAt = documentDescUpdatedAt.Default.(func() time.Time)
	// document.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	document.UpdateDefaultUpdatedAt = documentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// documentDescID is the schema descriptor for id field.
	documentDescID := documentMixinFields0[0].Descriptor()
	// document.DefaultID holds the default value on creation for the id field.
	document.DefaultID = documentDescID.Default.(func() uuid.UUID)
	documentsnapshotMixin := schema.DocumentSnapshot{}.Mixin()
	documentsnapshotMixinFields0 := documentsnapshotMixin[0].Fields()
	_ = documentsnapshotMixinFields0
	documentsnapshotFields := schema.DocumentSnapshot{}.Fields()
	_ = documentsnapshotFields
	// documentsnapshotDescCreatedAt is the schema descriptor for created_at field.
	documentsnapshotDescCreatedAt := documentsnapshotMixinFields0[1].Descriptor()
	// documentsnapshot.DefaultCreatedAt holds the default value on creation for the created_at field.
	documentsnapshot.DefaultCreatedAt = documentsnapshotDescCreatedAt.Default.(func() time.Time)
	// documentsnapshotDescID is the schema descriptor for id field.
	documentsnapshotDescID := documentsnapshotMixinFields0[0].Descriptor()
	// documentsnapshot.DefaultID holds the default value on creation for the id field.
	documentsnapshot.DefaultID = documentsnapshotDescID.Default.(func() uuid.UUID)
	oauthauthcodeMixin := schema.OAuthAuthCode{}.Mixin()
	oauthauthcodeMixinFields0 := oauthauthcodeMixin[0].Fields()
	_ = oauthauthcodeMixinFields0
	oauthauthcodeFields := schema.OAuthAuthCode{}.Fields()
	_ = oauthauthcodeFields
	// oauthauthcodeDescCreatedAt is the schema descriptor for created_at field.
	oauthauthcodeDescCreatedAt := oauthauthcodeMixinFields0[1].Descriptor()
	// oauthauthcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthauthcode.DefaultCreatedAt = oauthauthcodeDescCreatedAt.Default.(func() time.Time)
	// oauthauthcodeDescCode is the schema descriptor for code field.
	oauthauthcodeDescCode := oauthauthcodeFields[0].Descriptor()
	// oauthauthcode.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	oauthauthcode.CodeValidator = oauthauthcodeDescCode.Validators[0].(func(string) error)
	// oauthauthcodeDescClientID is the schema descriptor for client_id field.
	oauthauthcodeDescClientID := oauthauthcodeFields[1].Descriptor()
	// oauthauthcode.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthauthcode.ClientIDValidator = oauthauthcodeDescClientID.Validators[0].(func(string) error)
	// oauthauthcodeDescRedirectURI is the schema descriptor for redirect_uri field.
	oauthauthcodeDescRedirectURI := oauthauthcodeFields[2].Descriptor()
	// oauthauthcode.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	oauthauthcode.RedirectURIValidator = oauthauthcodeDescRedirectURI.Validators[0].(func(string) error)
	// oauthauthcodeDescUserID is the schema descriptor for user_id field.
	oauthauthcodeDescUserID := oauthauthcodeFields[8].Descriptor()
	// oauthauthcode.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	oauthauthcode.UserIDValidator = oauthauthcodeDescUserID.Validators[0].(func(string) error)
	// oauthauthcodeDescUsed is the schema descriptor for used field.
	oauthauthcodeDescUsed := oauthauthcodeFields[11].Descriptor()
	// oauthauthcode.DefaultUsed holds the default value on creation for the used field.
	oauthauthcode.DefaultUsed = oauthauthcodeDescUsed.Default.(bool)
	// oauthauthcodeDescID is the schema descriptor for id field.
	oauthauthcodeDescID := oauthauthcodeMixinFields0[0].Descriptor()
	// oauthauthcode.DefaultID holds the default value on creation for the id field.
	oauthauthcode.DefaultID = oauthauthcodeDescID.Default.(func() uuid.UUID)
	oauthauthstateMixin := schema.OAuthAuthState{}.Mixin()
	oauthauthstateMixinFields0 := oauthauthstateMixin[0].Fields()
	_ = oauthauthstateMixinFields0
	oauthauthstateFields := schema.OAuthAuthState{}.Fields()
	_ = oauthauthstateFields
	// oauthauthstateDescCreatedAt is the schema descriptor for created_at field.
	oauthauthstateDescCreatedAt := oauthauthstateMixinFields0[1].Descriptor()
	// oauthauthstate.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthauthstate.DefaultCreatedAt = oauthauthstateDescCreatedAt.Default.(func() time.Time)
	// oauthauthstateDescStateID is the schema descriptor for state_id field.
	oauthauthstateDescStateID := oauthauthstateFields[0].Descriptor()
	// oauthauthstate.StateIDValidator is a validator for the "state_id" field. It is called by the builders before save.
	oauthauthstate.StateIDValidator = oauthauthstateDescStateID.Validators[0].(func(string) error)
	// oauthauthstateDescClientID is the schema descriptor for client_id field.
	oauthauthstateDescClientID := oauthauthstateFields[2].Descriptor()
	// oauthauthstate.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthauthstate.ClientIDValidator = oauthauthstateDescClientID.Validators[0].(func(string) error)
	// oauthauthstateDescRedirectURI is the schema descriptor for redirect_uri field.
	oauthauthstateDescRedirectURI := oauthauthstateFields[3].Descriptor()
	// oauthauthstate.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	oauthauthstate.RedirectURIValidator = oauthauthstateDescRedirectURI.Validators[0].(func(string) error)
	// oauthauthstateDescProviderState is the schema descriptor for provider_state field.
	oauthauthstateDescProviderState := oauthauthstateFields[8].Descriptor()
	// oauthauthstate.ProviderStateValidator is a validator for the "provider_state" field. It is called by the builders before save.
	oauthauthstate.ProviderStateValidator = oauthauthstateDescProviderState.Validators[0].(func(string) error)
	// oauthauthstateDescProviderCodeVerifier is the schema descriptor for provider_code_verifier field.
	oauthauthstateDescProviderCodeVerifier := oauthauthstateFields[9].Descriptor()
	// oauthauthstate.ProviderCodeVerifierValidator is a validator for the "provider_code_verifier" field. It is called by the builders before save.
	oauthauthstate.ProviderCodeVerifierValidator = oauthauthstateDescProviderCodeVerifier.Validators[0].(func(string) error)
	// oauthauthstateDescID is the schema descriptor for id field.
	oauthauthstateDescID := oauthauthstateMixinFields0[0].Descriptor()
	// oauthauthstate.DefaultID holds the default value on creation for the id field.
	oauthauthstate.DefaultID = oauthauthstateDescID.Default.(func() uuid.UUID)
	oauthclientMixin := schema.OAuthClient{}.Mixin()
	oauthclientMixinFields0 := oauthclientMixin[0].Fields()
	_ = oauthclientMixinFields0
	oauthclientFields := schema.OAuthClient{}.Fields()
	_ = oauthclientFields
	// oauthclientDescCreatedAt is the schema descriptor for created_at field.
	oauthclientDescCreatedAt := oauthclientMixinFields0[1].Descriptor()
	// oauthclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthclient.DefaultCreatedAt = oauthclientDescCreatedAt.Default.(func() time.Time)
	// oauthclientDescClientID is the schema descriptor for client_id field.
	oauthclientDescClientID := oauthclientFields[0].Descriptor()
	// oauthclient.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthclient.ClientIDValidator = oauthclientDescClientID.Validators[0].(func(string) error)
	// oauthclientDescClientType is the schema descriptor for client_type field.
	oauthclientDescClientType := oauthclientFields[2].Descriptor()
	// oauthclient.ClientTypeValidator is a validator for the "client_type" field. It is called by the builders before save.
	oauthclient.ClientTypeValidator = oauthclientDescClientType.Validators[0].(func(string) error)
	// oauthclientDescTokenEndpointAuthMethod is the schema descriptor for token_endpoint_auth_method field.
	oauthclientDescTokenEndpointAuthMethod := oauthclientFields[4].Descriptor()
	// oauthclient.TokenEndpointAuthMethodValidator is a validator for the "token_endpoint_auth_method" field. It is called by the builders before save.
	oauthclient.TokenEndpointAuthMethodValidator = oauthclientDescTokenEndpointAuthMethod.Validators[0].(func(string) error)
	// oauthclientDescClientName is the schema descriptor for client_name field.
	oauthclientDescClientName := oauthclientFields[7].Descriptor()
	// oauthclient.ClientNameValidator is a validator for the "client_name" field. It is called by the builders before save.
	oauthclient.ClientNameValidator = oauthclientDescClientName.Validators[0].(func(string) error)
	// oauthclientDescUpdatedAt is the schema descriptor for updated_at field.
	oauthclientDescUpdatedAt := oauthclientFields[11].Descriptor()
	// oauthclient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthclient.DefaultUpdatedAt = oauthclientDescUpdatedAt.Default.(func() time.Time)
	// oauthclient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthclient.UpdateDefaultUpdatedAt = oauthclientDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthclientDescID is the schema descriptor for id field.
	oauthclientDescID := oauthclientMixinFields0[0].Descriptor()
	// oauthclient.DefaultID holds the default value on creation for the id field.
	oauthclient.DefaultID = oauthclientDescID.Default.(func() uuid.UUID)
	oauthprovidertokenMixin := schema.OAuthProviderToken{}.Mixin()
	oauthprovidertokenMixinFields0 := oauthprovidertokenMixin[0].Fields()
	_ = oauthprovidertokenMixinFields0
	oauthprovidertokenFields := schema.OAuthProviderToken{}.Fields()
	_ = oauthprovidertokenFields
	// oauthprovidertokenDescCreatedAt is the schema descriptor for created_at field.
	oauthprovidertokenDescCreatedAt := oauthprovidertokenMixinFields0[1].Descriptor()
	// oauthprovidertoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthprovidertoken.DefaultCreatedAt = oauthprovidertokenDescCreatedAt.Default.(func() time.Time)
	// oauthprovidertokenDescUserID is the schema descriptor for user_id field.
	oauthprovidertokenDescUserID := oauthprovidertokenFields[0].Descriptor()
	// oauthprovidertoken.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	oauthprovidertoken.UserIDValidator = oauthprovidertokenDescUserID.Validators[0].(func(string) error)
	// oauthprovidertokenDescTokenJSON is the schema descriptor for token_json field.
	oauthprovidertokenDescTokenJSON := oauthprovidertokenFields[1].Descriptor()
	// oauthprovidertoken.TokenJSONValidator is a validator for the "token_json" field. It is called by the builders before save.
	oauthprovidertoken.TokenJSONValidator = oauthprovidertokenDescTokenJSON.Validators[0].(func(string) error)
	// oauthprovidertokenDescUpdatedAt is the schema descriptor for updated_at field.
	oauthprovidertokenDescUpdatedAt := oauthprovidertokenFields[3].Descriptor()
	// oauthprovidertoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthprovidertoken.DefaultUpdatedAt = oauthprovidertokenDescUpdatedAt.Default.(func() time.Time)
	// oauthprovidertoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthprovidertoken.UpdateDefaultUpdatedAt = oauthprovidertokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthprovidertokenDescID is the schema descriptor for id field.
	oauthprovidertokenDescID := oauthprovidertokenMixinFields0[0].Descriptor()
	// oauthprovidertoken.DefaultID holds the default value on creation for the id field.
	oauthprovidertoken.DefaultID = oauthprovidertokenDescID.Default.(func() uuid.UUID)
	oauthrefreshfamilyMixin := schema.OAuthRefreshFamily{}.Mixin()
	oauthrefreshfamilyMixinFields0 := oauthrefreshfamilyMixin[0].Fields()
	_ = oauthrefreshfamilyMixinFields0
	oauthrefreshfamilyFields := schema.OAuthRefreshFamily{}.Fields()
	_ = oauthrefreshfamilyFields
	// oauthrefreshfamilyDescCreatedAt is the schema descriptor for created_at field.
	oauthrefreshfamilyDescCreatedAt := oauthrefreshfamilyMixinFields0[1].Descriptor()
	// oauthrefreshfamily.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthrefreshfamily.DefaultCreatedAt = oauthrefreshfamilyDescCreatedAt.Default.(func() time.Time)
	// oauthrefreshfamilyDescFamilyID is the schema descriptor for family_id field.
	oauthrefreshfamilyDescFamilyID := oauthrefreshfamilyFields[0].Descriptor()
	// oauthrefreshfamily.FamilyIDValidator is a validator for the "family_id" field. It is called by the builders before save.
	oauthrefreshfamily.FamilyIDValidator = oauthrefreshfamilyDescFamilyID.Validators[0].(func(string) error)
	// oauthrefreshfamilyDescUserID is the schema descriptor for user_id field.
	oauthrefreshfamilyDescUserID := oauthrefreshfamilyFields[1].Descriptor()
	// oauthrefreshfamily.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	oauthrefreshfamily.UserIDValidator = oauthrefreshfamilyDescUserID.Validators[0].(func(string) error)
	// oauthrefreshfamilyDescClientID is the schema descriptor for client_id field.
	oauthrefreshfamilyDescClientID := oauthrefreshfamilyFields[2].Descriptor()
	// oauthrefreshfamily.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthrefreshfamily.ClientIDValidator = oauthrefreshfamilyDescClientID.Validators[0].(func(string) error)
	// oauthrefreshfamilyDescRevoked is the schema descriptor for revoked field.
	oauthrefreshfamilyDescRevoked := oauthrefreshfamilyFields[5].Descriptor()
	// oauthrefreshfamily.DefaultRevoked holds the default value on creation for the revoked field.
	oauthrefreshfamily.DefaultRevoked = oauthrefreshfamilyDescRevoked.Default.(bool)
	// oauthrefreshfamilyDescID is the schema descriptor for id field.
	oauthrefreshfamilyDescID := oauthrefreshfamilyMixinFields0[0].Descriptor()
	// oauthrefreshfamily.DefaultID holds the default value on creation for the id field.
	oauthrefreshfamily.DefaultID = oauthrefreshfamilyDescID.Default.(func() uuid.UUID)
	oauthrefreshtokenMixin := schema.OAuthRefreshToken{}.Mixin()
	oauthrefreshtokenMixinFields0 := oauthrefreshtokenMixin[0].Fields()
	_ = oauthrefreshtokenMixinFields0
	oauthrefreshtokenFields := schema.OAuthRefreshToken{}.Fields()
	_ = oauthrefreshtokenFields
	// oauthrefreshtokenDescCreatedAt is the schema descriptor for created_at field.
	oauthrefreshtokenDescCreatedAt := oauthrefreshtokenMixinFields0[1].Descriptor()
	// oauthrefreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthrefreshtoken.DefaultCreatedAt = oauthrefreshtokenDescCreatedAt.Default.(func() time.Time)
	// oauthrefreshtokenDescTokenHash is the schema descriptor for token_hash field.
	oauthrefreshtokenDescTokenHash := oauthrefreshtokenFields[0].Descriptor()
	// oauthrefreshtoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	oauthrefreshtoken.TokenHashValidator = oauthrefreshtokenDescTokenHash.Validators[0].(func(string) error)
	// oauthrefreshtokenDescUserID is the schema descriptor for user_id field.
	oauthrefreshtokenDescUserID := oauthrefreshtokenFields[1].Descriptor()
	// oauthrefreshtoken.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	oauthrefreshtoken.UserIDValidator = oauthrefreshtokenDescUserID.Validators[0].(func(string) error)
	// oauthrefreshtokenDescGeneration is the schema descriptor for generation field.
	oauthrefreshtokenDescGeneration := oauthrefreshtokenFields[4].Descriptor()
	// oauthrefreshtoken.DefaultGeneration holds the default value on creation for the generation field.
	oauthrefreshtoken.DefaultGeneration = oauthrefreshtokenDescGeneration.Default.(int)
	// oauthrefreshtokenDescID is the schema descriptor for id field.
	oauthrefreshtokenDescID := oauthrefreshtokenMixinFields0[0].Descriptor()
	// oauthrefreshtoken.DefaultID holds the default value on creation for the id field.
	oauthrefreshtoken.DefaultID = oauthrefreshtokenDescID.Default.(func() uuid.UUID)
	oauthrevokedjtiMixin := schema.OAuthRevokedJTI{}.Mixin()
	oauthrevokedjtiMixinFields0 := oauthrevokedjtiMixin[0].Fields()
	_ = oauthrevokedjtiMixinFields0
	oauthrevokedjtiFields := schema.OAuthRevokedJTI{}.Fields()
	_ = oauthrevokedjtiFields
	// oauthrevokedjtiDescCreatedAt is the schema descriptor for created_at field.
	oauthrevokedjtiDescCreatedAt := oauthrevokedjtiMixinFields0[1].Descriptor()
	// oauthrevokedjti.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthrevokedjti.DefaultCreatedAt = oauthrevokedjtiDescCreatedAt.Default.(func() time.Time)
	// oauthrevokedjtiDescJti is the schema descriptor for jti field.
	oauthrevokedjtiDescJti := oauthrevokedjtiFields[0].Descriptor()
	// oauthrevokedjti.JtiValidator is a validator for the "jti" field. It is called by the builders before save.
	oauthrevokedjti.JtiValidator = oauthrevokedjtiDescJti.Validators[0].(func(string) error)
	// oauthrevokedjtiDescID is the schema descriptor for id field.
	oauthrevokedjtiDescID := oauthrevokedjtiMixinFields0[0].Descriptor()
	// oauthrevokedjti.DefaultID holds the default value on creation for the id field.
	oauthrevokedjti.DefaultID = oauthrevokedjtiDescID.Default.(func() uuid.UUID)
	oauthtokenmetadataMixin := schema.OAuthTokenMetadata{}.Mixin()
	oauthtokenmetadataMixinFields0 := oauthtokenmetadataMixin[0].Fields()
	_ = oauthtokenmetadataMixinFields0
	oauthtokenmetadataFields := schema.OAuthTokenMetadata{}.Fields()
	_ = oauthtokenmetadataFields
	// oauthtokenmetadataDescCreatedAt is the schema descriptor for created_at field.
	oauthtokenmetadataDescCreatedAt := oauthtokenmetadataMixinFields0[1].Descriptor()
	// oauthtokenmetadata.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthtokenmetadata.DefaultCreatedAt = oauthtokenmetadataDescCreatedAt.Default.(func() time.Time)
	// oauthtokenmetadataDescTokenID is the schema descriptor for token_id field.
	oauthtokenmetadataDescTokenID := oauthtokenmetadataFields[0].Descriptor()
	// oauthtokenmetadata.TokenIDValidator is a validator for the "token_id" field. It is called by the builders before save.
	oauthtokenmetadata.TokenIDValidator = oauthtokenmetadataDescTokenID.Validators[0].(func(string) error)
	// oauthtokenmetadataDescUserID is the schema descriptor for user_id field.
	oauthtokenmetadataDescUserID := oauthtokenmetadataFields[1].Descriptor()
	// oauthtokenmetadata.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	oauthtokenmetadata.UserIDValidator = oauthtokenmetadataDescUserID.Validators[0].(func(string) error)
	// oauthtokenmetadataDescClientID is the schema descriptor for client_id field.
	oauthtokenmetadataDescClientID := oauthtokenmetadataFields[2].Descriptor()
	// oauthtokenmetadata.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	oauthtokenmetadata.ClientIDValidator = oauthtokenmetadataDescClientID.Validators[0].(func(string) error)
	// oauthtokenmetadataDescTokenType is the schema descriptor for token_type field.
	oauthtokenmetadataDescTokenType := oauthtokenmetadataFields[5].Descriptor()
	// oauthtokenmetadata.TokenTypeValidator is a validator for the "token_type" field. It is called by the builders before save.
	oauthtokenmetadata.TokenTypeValidator = oauthtokenmetadataDescTokenType.Validators[0].(func(string) error)
	// oauthtokenmetadataDescID is the schema descriptor for id field.
	oauthtokenmetadataDescID := oauthtokenmetadataMixinFields0[0].Descriptor()
	// oauthtokenmetadata.DefaultID holds the default value on creation for the id field.
	oauthtokenmetadata.DefaultID = oauthtokenmetadataDescID.Default.(func() uuid.UUID)
	oauthuserinfoMixin := schema.OAuthUserInfo{}.Mixin()
	oauthuserinfoMixinFields0 := oauthuserinfoMixin[0].Fields()
	_ = oauthuserinfoMixinFields0
	oauthuserinfoFields := schema.OAuthUserInfo{}.Fields()
	_ = oauthuserinfoFields
	// oauthuserinfoDescCreatedAt is the schema descriptor for created_at field.
	oauthuserinfoDescCreatedAt := oauthuserinfoMixinFields0[1].Descriptor()
	// oauthuserinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthuserinfo.DefaultCreatedAt = oauthuserinfoDescCreatedAt.Default.(func() time.Time)
	// oauthuserinfoDescUserID is the schema descriptor for user_id field.
	oauthuserinfoDescUserID := oauthuserinfoFields[0].Descriptor()
	// oauthuserinfo.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	oauthuserinfo.UserIDValidator = oauthuserinfoDescUserID.Validators[0].(func(string) error)
	// oauthuserinfoDescInfoJSON is the schema descriptor for info_json field.
	oauthuserinfoDescInfoJSON := oauthuserinfoFields[1].Descriptor()
	// oauthuserinfo.InfoJSONValidator is a validator for the "info_json" field. It is called by the builders before save.
	oauthuserinfo.InfoJSONValidator = oauthuserinfoDescInfoJSON.Validators[0].(func(string) error)
	// oauthuserinfoDescUpdatedAt is the schema descriptor for updated_at field.
	oauthuserinfoDescUpdatedAt := oauthuserinfoFields[3].Descriptor()
	// oauthuserinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthuserinfo.DefaultUpdatedAt = oauthuserinfoDescUpdatedAt.Default.(func() time.Time)
	// oauthuserinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthuserinfo.UpdateDefaultUpdatedAt = oauthuserinfoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthuserinfoDescID is the schema descriptor for id field.
	oauthuserinfoDescID := oauthuserinfoMixinFields0[0].Descriptor()
	// oauthuserinfo.DefaultID holds the default value on creation for the id field.
	oauthuserinfo.DefaultID = oauthuserinfoDescID.Default.(func() uuid.UUID)
	projectMixin := schema.Project{}.Mixin()
	projectMixinFields0 := projectMixin[0].Fields()
	_ = projectMixinFields0
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectMixinFields0[1].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[0].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescArchived is the schema descriptor for archived field.
	projectDescArchived := projectFields[3].Descriptor()
	// project.DefaultArchived holds the default value on creation for the archived field.
	project.DefaultArchived = projectDescArchived.Default.(bool)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[4].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectMixinFields0[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	projectgroupshareMixin := schema.ProjectGroupShare{}.Mixin()
	projectgroupshareMixinFields0 := projectgroupshareMixin[0].Fields()
	_ = projectgroupshareMixinFields0
	projectgroupshareFields := schema.ProjectGroupShare{}.Fields()
	_ = projectgroupshareFields
	// projectgroupshareDescCreatedAt is the schema descriptor for created_at field.
	projectgroupshareDescCreatedAt := projectgroupshareMixinFields0[1].Descriptor()
	// projectgroupshare.DefaultCreatedAt holds the default value on creation for the created_at field.
	projectgroupshare.DefaultCreatedAt = projectgroupshareDescCreatedAt.Default.(func() time.Time)
	// projectgroupshareDescGroupName is the schema descriptor for group_name field.
	projectgroupshareDescGroupName := projectgroupshareFields[0].Descriptor()
	// projectgroupshare.GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	projectgroupshare.GroupNameValidator = projectgroupshareDescGroupName.Validators[0].(func(string) error)
	// projectgroupshareDescID is the schema descriptor for id field.
	projectgroupshareDescID := projectgroupshareMixinFields0[0].Descriptor()
	// projectgroupshare.DefaultID holds the default value on creation for the id field.
	projectgroupshare.DefaultID = projectgroupshareDescID.Default.(func() uuid.UUID)
	projectshareMixin := schema.ProjectShare{}.Mixin()
	projectshareMixinFields0 := projectshareMixin[0].Fields()
	_ = projectshareMixinFields0
	projectshareFields := schema.ProjectShare{}.Fields()
	_ = projectshareFields
	// projectshareDescCreatedAt is the schema descriptor for created_at field.
	projectshareDescCreatedAt := projectshareMixinFields0[1].Descriptor()
	// projectshare.DefaultCreatedAt holds the default value on creation for the created_at field.
	projectshare.DefaultCreatedAt = projectshareDescCreatedAt.Default.(func() time.Time)
	// projectshareDescID is the schema descriptor for id field.
	projectshareDescID := projectshareMixinFields0[0].Descriptor()
	// projectshare.DefaultID holds the default value on creation for the id field.
	projectshare.DefaultID = projectshareDescID.Default.(func() uuid.UUID)
	sessionMixin := schema.Session{}.Mixin()
	sessionMixinFields0 := sessionMixin[0].Fields()
	_ = sessionMixinFields0
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionMixinFields0[1].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescTokenHash is the schema descriptor for token_hash field.
	sessionDescTokenHash := sessionFields[0].Descriptor()
	// session.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	session.TokenHashValidator = sessionDescTokenHash.Validators[0].(func(string) error)
	// sessionDescSubject is the schema descriptor for subject field.
	sessionDescSubject := sessionFields[1].Descriptor()
	// session.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	session.SubjectValidator = sessionDescSubject.Validators[0].(func(string) error)
	// sessionDescEmail is the schema descriptor for email field.
	sessionDescEmail := sessionFields[2].Descriptor()
	// session.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	session.EmailValidator = sessionDescEmail.Validators[0].(func(string) error)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionMixinFields0[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	tenantMixin := schema.Tenant{}.Mixin()
	tenantMixinFields0 := tenantMixin[0].Fields()
	_ = tenantMixinFields0
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantMixinFields0[1].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescKey is the schema descriptor for key field.
	tenantDescKey := tenantFields[0].Descriptor()
	// tenant.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	tenant.KeyValidator = tenantDescKey.Validators[0].(func(string) error)
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantMixinFields0[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescExternalSubject is the schema descriptor for external_subject field.
	userDescExternalSubject := userFields[0].Descriptor()
	// user.ExternalSubjectValidator is a validator for the "external_subject" field. It is called by the builders before save.
	user.ExternalSubjectValidator = userDescExternalSubject.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
