// Code generated by ent, DO NOT EDIT.

package oauthauthstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the oauthauthstate type in the database.
	Label = "oauth_auth_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldStateID holds the string denoting the state_id field in the database.
	FieldStateID = "state_id"
	// FieldOriginalClientState holds the string denoting the original_client_state field in the database.
	FieldOriginalClientState = "original_client_state"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldRedirectURI holds the string denoting the redirect_uri field in the database.
	FieldRedirectURI = "redirect_uri"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldResource holds the string denoting the resource field in the database.
	FieldResource = "resource"
	// FieldCodeChallenge holds the string denoting the code_challenge field in the database.
	FieldCodeChallenge = "code_challenge"
	// FieldCodeChallengeMethod holds the string denoting the code_challenge_method field in the database.
	FieldCodeChallengeMethod = "code_challenge_method"
	// FieldProviderState holds the string denoting the provider_state field in the database.
	FieldProviderState = "provider_state"
	// FieldProviderCodeVerifier holds the string denoting the provider_code_verifier field in the database.
	FieldProviderCodeVerifier = "provider_code_verifier"
	// FieldNonce holds the string denoting the nonce field in the database.
	FieldNonce = "nonce"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the oauthauthstate in the database.
	Table = "oauth_auth_states"
)

// Columns holds all SQL columns for oauthauthstate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldStateID,
	FieldOriginalClientState,
	FieldClientID,
	FieldRedirectURI,
	FieldScope,
	FieldResource,
	FieldCodeChallenge,
	FieldCodeChallengeMethod,
	FieldProviderState,
	FieldProviderCodeVerifier,
	FieldNonce,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// StateIDValidator is a validator for the "state_id" field. It is called by the builders before save.
	StateIDValidator func(string) error
	// ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	ClientIDValidator func(string) error
	// RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	RedirectURIValidator func(string) error
	// ProviderStateValidator is a validator for the "provider_state" field. It is called by the builders before save.
	ProviderStateValidator func(string) error
	// ProviderCodeVerifierValidator is a validator for the "provider_code_verifier" field. It is called by the builders before save.
	ProviderCodeVerifierValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the OAuthAuthState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByStateID orders the results by the state_id field.
func ByStateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStateID, opts...).ToFunc()
}

// ByOriginalClientState orders the results by the original_client_state field.
func ByOriginalClientState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalClientState, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByRedirectURI orders the results by the redirect_uri field.
func ByRedirectURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedirectURI, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByResource orders the results by the resource field.
func ByResource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResource, opts...).ToFunc()
}

// ByCodeChallenge orders the results by the code_challenge field.
func ByCodeChallenge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeChallenge, opts...).ToFunc()
}

// ByCodeChallengeMethod orders the results by the code_challenge_method field.
func ByCodeChallengeMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeChallengeMethod, opts...).ToFunc()
}

// ByProviderState orders the results by the provider_state field.
func ByProviderState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderState, opts...).ToFunc()
}

// ByProviderCodeVerifier orders the results by the provider_code_verifier field.
func ByProviderCodeVerifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderCodeVerifier, opts...).ToFunc()
}

// ByNonce orders the results by the nonce field.
func ByNonce(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNonce, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
