// Code generated by ent, DO NOT EDIT.

package oauthauthstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldCreatedAt, v))
}

// StateID applies equality check predicate on the "state_id" field. It's identical to StateIDEQ.
func StateID(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldStateID, v))
}

// OriginalClientState applies equality check predicate on the "original_client_state" field. It's identical to OriginalClientStateEQ.
func OriginalClientState(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldOriginalClientState, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldClientID, v))
}

// RedirectURI applies equality check predicate on the "redirect_uri" field. It's identical to RedirectURIEQ.
func RedirectURI(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldRedirectURI, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldScope, v))
}

// Resource applies equality check predicate on the "resource" field. It's identical to ResourceEQ.
func Resource(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldResource, v))
}

// CodeChallenge applies equality check predicate on the "code_challenge" field. It's identical to CodeChallengeEQ.
func CodeChallenge(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldCodeChallenge, v))
}

// CodeChallengeMethod applies equality check predicate on the "code_challenge_method" field. It's identical to CodeChallengeMethodEQ.
func CodeChallengeMethod(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldCodeChallengeMethod, v))
}

// ProviderState applies equality check predicate on the "provider_state" field. It's identical to ProviderStateEQ.
func ProviderState(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldProviderState, v))
}

// ProviderCodeVerifier applies equality check predicate on the "provider_code_verifier" field. It's identical to ProviderCodeVerifierEQ.
func ProviderCodeVerifier(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldProviderCodeVerifier, v))
}

// Nonce applies equality check predicate on the "nonce" field. It's identical to NonceEQ.
func Nonce(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldNonce, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldCreatedAt, v))
}

// StateIDEQ applies the EQ predicate on the "state_id" field.
func StateIDEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldStateID, v))
}

// StateIDNEQ applies the NEQ predicate on the "state_id" field.
func StateIDNEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldStateID, v))
}

// StateIDIn applies the In predicate on the "state_id" field.
func StateIDIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldStateID, vs...))
}

// StateIDNotIn applies the NotIn predicate on the "state_id" field.
func StateIDNotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldStateID, vs...))
}

// StateIDGT applies the GT predicate on the "state_id" field.
func StateIDGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldStateID, v))
}

// StateIDGTE applies the GTE predicate on the "state_id" field.
func StateIDGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldStateID, v))
}

// StateIDLT applies the LT predicate on the "state_id" field.
func StateIDLT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldStateID, v))
}

// StateIDLTE applies the LTE predicate on the "state_id" field.
func StateIDLTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldStateID, v))
}

// StateIDContains applies the Contains predicate on the "state_id" field.
func StateIDContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldStateID, v))
}

// StateIDHasPrefix applies the HasPrefix predicate on the "state_id" field.
func StateIDHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldStateID, v))
}

// StateIDHasSuffix applies the HasSuffix predicate on the "state_id" field.
func StateIDHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldStateID, v))
}

// StateIDEqualFold applies the EqualFold predicate on the "state_id" field.
func StateIDEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldStateID, v))
}

// StateIDContainsFold applies the ContainsFold predicate on the "state_id" field.
func StateIDContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldStateID, v))
}

// OriginalClientStateEQ applies the EQ predicate on the "original_client_state" field.
func OriginalClientStateEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldOriginalClientState, v))
}

// OriginalClientStateNEQ applies the NEQ predicate on the "original_client_state" field.
func OriginalClientStateNEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldOriginalClientState, v))
}

// OriginalClientStateIn applies the In predicate on the "original_client_state" field.
func OriginalClientStateIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldOriginalClientState, vs...))
}

// OriginalClientStateNotIn applies the NotIn predicate on the "original_client_state" field.
func OriginalClientStateNotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldOriginalClientState, vs...))
}

// OriginalClientStateGT applies the GT predicate on the "original_client_state" field.
func OriginalClientStateGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldOriginalClientState, v))
}

// OriginalClientStateGTE applies the GTE predicate on the "original_client_state" field.
func OriginalClientStateGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldOriginalClientState, v))
}

// OriginalClientStateLT applies the LT predicate on the "original_client_state" field.
func OriginalClientStateLT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldOriginalClientState, v))
}

// OriginalClientStateLTE applies the LTE predicate on the "original_client_state" field.
func OriginalClientStateLTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldOriginalClientState, v))
}

// OriginalClientStateContains applies the Contains predicate on the "original_client_state" field.
func OriginalClientStateContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldOriginalClientState, v))
}

// OriginalClientStateHasPrefix applies the HasPrefix predicate on the "original_client_state" field.
func OriginalClientStateHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldOriginalClientState, v))
}

// OriginalClientStateHasSuffix applies the HasSuffix predicate on the "original_client_state" field.
func OriginalClientStateHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldOriginalClientState, v))
}

// OriginalClientStateIsNil applies the IsNil predicate on the "original_client_state" field.
func OriginalClientStateIsNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIsNull(FieldOriginalClientState))
}

// OriginalClientStateNotNil applies the NotNil predicate on the "original_client_state" field.
func OriginalClientStateNotNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotNull(FieldOriginalClientState))
}

// OriginalClientStateEqualFold applies the EqualFold predicate on the "original_client_state" field.
func OriginalClientStateEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldOriginalClientState, v))
}

// OriginalClientStateContainsFold applies the ContainsFold predicate on the "original_client_state" field.
func OriginalClientStateContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldOriginalClientState, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldClientID, v))
}

// RedirectURIEQ applies the EQ predicate on the "redirect_uri" field.
func RedirectURIEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldRedirectURI, v))
}

// RedirectURINEQ applies the NEQ predicate on the "redirect_uri" field.
func RedirectURINEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldRedirectURI, v))
}

// RedirectURIIn applies the In predicate on the "redirect_uri" field.
func RedirectURIIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldRedirectURI, vs...))
}

// RedirectURINotIn applies the NotIn predicate on the "redirect_uri" field.
func RedirectURINotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldRedirectURI, vs...))
}

// RedirectURIGT applies the GT predicate on the "redirect_uri" field.
func RedirectURIGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldRedirectURI, v))
}

// RedirectURIGTE applies the GTE predicate on the "redirect_uri" field.
func RedirectURIGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldRedirectURI, v))
}

// RedirectURILT applies the LT predicate on the "redirect_uri" field.
func RedirectURILT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldRedirectURI, v))
}

// RedirectURILTE applies the LTE predicate on the "redirect_uri" field.
func RedirectURILTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldRedirectURI, v))
}

// RedirectURIContains applies the Contains predicate on the "redirect_uri" field.
func RedirectURIContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldRedirectURI, v))
}

// RedirectURIHasPrefix applies the HasPrefix predicate on the "redirect_uri" field.
func RedirectURIHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldRedirectURI, v))
}

// RedirectURIHasSuffix applies the HasSuffix predicate on the "redirect_uri" field.
func RedirectURIHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldRedirectURI, v))
}

// RedirectURIEqualFold applies the EqualFold predicate on the "redirect_uri" field.
func RedirectURIEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldRedirectURI, v))
}

// RedirectURIContainsFold applies the ContainsFold predicate on the "redirect_uri" field.
func RedirectURIContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldRedirectURI, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeIsNil applies the IsNil predicate on the "scope" field.
func ScopeIsNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIsNull(FieldScope))
}

// ScopeNotNil applies the NotNil predicate on the "scope" field.
func ScopeNotNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotNull(FieldScope))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldScope, v))
}

// ResourceEQ applies the EQ predicate on the "resource" field.
func ResourceEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldResource, v))
}

// ResourceNEQ applies the NEQ predicate on the "resource" field.
func ResourceNEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldResource, v))
}

// ResourceIn applies the In predicate on the "resource" field.
func ResourceIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldResource, vs...))
}

// ResourceNotIn applies the NotIn predicate on the "resource" field.
func ResourceNotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldResource, vs...))
}

// ResourceGT applies the GT predicate on the "resource" field.
func ResourceGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldResource, v))
}

// ResourceGTE applies the GTE predicate on the "resource" field.
func ResourceGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldResource, v))
}

// ResourceLT applies the LT predicate on the "resource" field.
func ResourceLT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldResource, v))
}

// ResourceLTE applies the LTE predicate on the "resource" field.
func ResourceLTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldResource, v))
}

// ResourceContains applies the Contains predicate on the "resource" field.
func ResourceContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldResource, v))
}

// ResourceHasPrefix applies the HasPrefix predicate on the "resource" field.
func ResourceHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldResource, v))
}

// ResourceHasSuffix applies the HasSuffix predicate on the "resource" field.
func ResourceHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldResource, v))
}

// ResourceIsNil applies the IsNil predicate on the "resource" field.
func ResourceIsNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIsNull(FieldResource))
}

// ResourceNotNil applies the NotNil predicate on the "resource" field.
func ResourceNotNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotNull(FieldResource))
}

// ResourceEqualFold applies the EqualFold predicate on the "resource" field.
func ResourceEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldResource, v))
}

// ResourceContainsFold applies the ContainsFold predicate on the "resource" field.
func ResourceContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldResource, v))
}

// CodeChallengeEQ applies the EQ predicate on the "code_challenge" field.
func CodeChallengeEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldCodeChallenge, v))
}

// CodeChallengeNEQ applies the NEQ predicate on the "code_challenge" field.
func CodeChallengeNEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldCodeChallenge, v))
}

// CodeChallengeIn applies the In predicate on the "code_challenge" field.
func CodeChallengeIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldCodeChallenge, vs...))
}

// CodeChallengeNotIn applies the NotIn predicate on the "code_challenge" field.
func CodeChallengeNotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldCodeChallenge, vs...))
}

// CodeChallengeGT applies the GT predicate on the "code_challenge" field.
func CodeChallengeGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldCodeChallenge, v))
}

// CodeChallengeGTE applies the GTE predicate on the "code_challenge" field.
func CodeChallengeGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldCodeChallenge, v))
}

// CodeChallengeLT applies the LT predicate on the "code_challenge" field.
func CodeChallengeLT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldCodeChallenge, v))
}

// CodeChallengeLTE applies the LTE predicate on the "code_challenge" field.
func CodeChallengeLTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldCodeChallenge, v))
}

// CodeChallengeContains applies the Contains predicate on the "code_challenge" field.
func CodeChallengeContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldCodeChallenge, v))
}

// CodeChallengeHasPrefix applies the HasPrefix predicate on the "code_challenge" field.
func CodeChallengeHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldCodeChallenge, v))
}

// CodeChallengeHasSuffix applies the HasSuffix predicate on the "code_challenge" field.
func CodeChallengeHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldCodeChallenge, v))
}

// CodeChallengeIsNil applies the IsNil predicate on the "code_challenge" field.
func CodeChallengeIsNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIsNull(FieldCodeChallenge))
}

// CodeChallengeNotNil applies the NotNil predicate on the "code_challenge" field.
func CodeChallengeNotNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotNull(FieldCodeChallenge))
}

// CodeChallengeEqualFold applies the EqualFold predicate on the "code_challenge" field.
func CodeChallengeEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldCodeChallenge, v))
}

// CodeChallengeContainsFold applies the ContainsFold predicate on the "code_challenge" field.
func CodeChallengeContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldCodeChallenge, v))
}

// CodeChallengeMethodEQ applies the EQ predicate on the "code_challenge_method" field.
func CodeChallengeMethodEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodNEQ applies the NEQ predicate on the "code_challenge_method" field.
func CodeChallengeMethodNEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodIn applies the In predicate on the "code_challenge_method" field.
func CodeChallengeMethodIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldCodeChallengeMethod, vs...))
}

// CodeChallengeMethodNotIn applies the NotIn predicate on the "code_challenge_method" field.
func CodeChallengeMethodNotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldCodeChallengeMethod, vs...))
}

// CodeChallengeMethodGT applies the GT predicate on the "code_challenge_method" field.
func CodeChallengeMethodGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodGTE applies the GTE predicate on the "code_challenge_method" field.
func CodeChallengeMethodGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodLT applies the LT predicate on the "code_challenge_method" field.
func CodeChallengeMethodLT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodLTE applies the LTE predicate on the "code_challenge_method" field.
func CodeChallengeMethodLTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodContains applies the Contains predicate on the "code_challenge_method" field.
func CodeChallengeMethodContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodHasPrefix applies the HasPrefix predicate on the "code_challenge_method" field.
func CodeChallengeMethodHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodHasSuffix applies the HasSuffix predicate on the "code_challenge_method" field.
func CodeChallengeMethodHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodIsNil applies the IsNil predicate on the "code_challenge_method" field.
func CodeChallengeMethodIsNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIsNull(FieldCodeChallengeMethod))
}

// CodeChallengeMethodNotNil applies the NotNil predicate on the "code_challenge_method" field.
func CodeChallengeMethodNotNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotNull(FieldCodeChallengeMethod))
}

// CodeChallengeMethodEqualFold applies the EqualFold predicate on the "code_challenge_method" field.
func CodeChallengeMethodEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodContainsFold applies the ContainsFold predicate on the "code_challenge_method" field.
func CodeChallengeMethodContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldCodeChallengeMethod, v))
}

// ProviderStateEQ applies the EQ predicate on the "provider_state" field.
func ProviderStateEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldProviderState, v))
}

// ProviderStateNEQ applies the NEQ predicate on the "provider_state" field.
func ProviderStateNEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldProviderState, v))
}

// ProviderStateIn applies the In predicate on the "provider_state" field.
func ProviderStateIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldProviderState, vs...))
}

// ProviderStateNotIn applies the NotIn predicate on the "provider_state" field.
func ProviderStateNotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldProviderState, vs...))
}

// ProviderStateGT applies the GT predicate on the "provider_state" field.
func ProviderStateGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldProviderState, v))
}

// ProviderStateGTE applies the GTE predicate on the "provider_state" field.
func ProviderStateGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldProviderState, v))
}

// ProviderStateLT applies the LT predicate on the "provider_state" field.
func ProviderStateLT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldProviderState, v))
}

// ProviderStateLTE applies the LTE predicate on the "provider_state" field.
func ProviderStateLTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldProviderState, v))
}

// ProviderStateContains applies the Contains predicate on the "provider_state" field.
func ProviderStateContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldProviderState, v))
}

// ProviderStateHasPrefix applies the HasPrefix predicate on the "provider_state" field.
func ProviderStateHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldProviderState, v))
}

// ProviderStateHasSuffix applies the HasSuffix predicate on the "provider_state" field.
func ProviderStateHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldProviderState, v))
}

// ProviderStateEqualFold applies the EqualFold predicate on the "provider_state" field.
func ProviderStateEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldProviderState, v))
}

// ProviderStateContainsFold applies the ContainsFold predicate on the "provider_state" field.
func ProviderStateContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldProviderState, v))
}

// ProviderCodeVerifierEQ applies the EQ predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldProviderCodeVerifier, v))
}

// ProviderCodeVerifierNEQ applies the NEQ predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierNEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldProviderCodeVerifier, v))
}

// ProviderCodeVerifierIn applies the In predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldProviderCodeVerifier, vs...))
}

// ProviderCodeVerifierNotIn applies the NotIn predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierNotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldProviderCodeVerifier, vs...))
}

// ProviderCodeVerifierGT applies the GT predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldProviderCodeVerifier, v))
}

// ProviderCodeVerifierGTE applies the GTE predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldProviderCodeVerifier, v))
}

// ProviderCodeVerifierLT applies the LT predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierLT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldProviderCodeVerifier, v))
}

// ProviderCodeVerifierLTE applies the LTE predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierLTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldProviderCodeVerifier, v))
}

// ProviderCodeVerifierContains applies the Contains predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldProviderCodeVerifier, v))
}

// ProviderCodeVerifierHasPrefix applies the HasPrefix predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldProviderCodeVerifier, v))
}

// ProviderCodeVerifierHasSuffix applies the HasSuffix predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldProviderCodeVerifier, v))
}

// ProviderCodeVerifierEqualFold applies the EqualFold predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldProviderCodeVerifier, v))
}

// ProviderCodeVerifierContainsFold applies the ContainsFold predicate on the "provider_code_verifier" field.
func ProviderCodeVerifierContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldProviderCodeVerifier, v))
}

// NonceEQ applies the EQ predicate on the "nonce" field.
func NonceEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldNonce, v))
}

// NonceNEQ applies the NEQ predicate on the "nonce" field.
func NonceNEQ(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldNonce, v))
}

// NonceIn applies the In predicate on the "nonce" field.
func NonceIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldNonce, vs...))
}

// NonceNotIn applies the NotIn predicate on the "nonce" field.
func NonceNotIn(vs ...string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldNonce, vs...))
}

// NonceGT applies the GT predicate on the "nonce" field.
func NonceGT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldNonce, v))
}

// NonceGTE applies the GTE predicate on the "nonce" field.
func NonceGTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldNonce, v))
}

// NonceLT applies the LT predicate on the "nonce" field.
func NonceLT(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldNonce, v))
}

// NonceLTE applies the LTE predicate on the "nonce" field.
func NonceLTE(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldNonce, v))
}

// NonceContains applies the Contains predicate on the "nonce" field.
func NonceContains(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContains(FieldNonce, v))
}

// NonceHasPrefix applies the HasPrefix predicate on the "nonce" field.
func NonceHasPrefix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasPrefix(FieldNonce, v))
}

// NonceHasSuffix applies the HasSuffix predicate on the "nonce" field.
func NonceHasSuffix(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldHasSuffix(FieldNonce, v))
}

// NonceIsNil applies the IsNil predicate on the "nonce" field.
func NonceIsNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIsNull(FieldNonce))
}

// NonceNotNil applies the NotNil predicate on the "nonce" field.
func NonceNotNil() predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotNull(FieldNonce))
}

// NonceEqualFold applies the EqualFold predicate on the "nonce" field.
func NonceEqualFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEqualFold(FieldNonce, v))
}

// NonceContainsFold applies the ContainsFold predicate on the "nonce" field.
func NonceContainsFold(v string) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldContainsFold(FieldNonce, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthAuthState) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthAuthState) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthAuthState) predicate.OAuthAuthState {
	return predicate.OAuthAuthState(sql.NotPredicates(p))
}
