// Code generated by ent, DO NOT EDIT.

package oauthprovidertoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldCreatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldUserID, v))
}

// TokenJSON applies equality check predicate on the "token_json" field. It's identical to TokenJSONEQ.
func TokenJSON(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldTokenJSON, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldExpiresAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLTE(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldContainsFold(FieldUserID, v))
}

// TokenJSONEQ applies the EQ predicate on the "token_json" field.
func TokenJSONEQ(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldTokenJSON, v))
}

// TokenJSONNEQ applies the NEQ predicate on the "token_json" field.
func TokenJSONNEQ(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNEQ(FieldTokenJSON, v))
}

// TokenJSONIn applies the In predicate on the "token_json" field.
func TokenJSONIn(vs ...string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldIn(FieldTokenJSON, vs...))
}

// TokenJSONNotIn applies the NotIn predicate on the "token_json" field.
func TokenJSONNotIn(vs ...string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNotIn(FieldTokenJSON, vs...))
}

// TokenJSONGT applies the GT predicate on the "token_json" field.
func TokenJSONGT(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGT(FieldTokenJSON, v))
}

// TokenJSONGTE applies the GTE predicate on the "token_json" field.
func TokenJSONGTE(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGTE(FieldTokenJSON, v))
}

// TokenJSONLT applies the LT predicate on the "token_json" field.
func TokenJSONLT(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLT(FieldTokenJSON, v))
}

// TokenJSONLTE applies the LTE predicate on the "token_json" field.
func TokenJSONLTE(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLTE(FieldTokenJSON, v))
}

// TokenJSONContains applies the Contains predicate on the "token_json" field.
func TokenJSONContains(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldContains(FieldTokenJSON, v))
}

// TokenJSONHasPrefix applies the HasPrefix predicate on the "token_json" field.
func TokenJSONHasPrefix(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldHasPrefix(FieldTokenJSON, v))
}

// TokenJSONHasSuffix applies the HasSuffix predicate on the "token_json" field.
func TokenJSONHasSuffix(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldHasSuffix(FieldTokenJSON, v))
}

// TokenJSONEqualFold applies the EqualFold predicate on the "token_json" field.
func TokenJSONEqualFold(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEqualFold(FieldTokenJSON, v))
}

// TokenJSONContainsFold applies the ContainsFold predicate on the "token_json" field.
func TokenJSONContainsFold(v string) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldContainsFold(FieldTokenJSON, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLTE(FieldExpiresAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthProviderToken) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthProviderToken) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthProviderToken) predicate.OAuthProviderToken {
	return predicate.OAuthProviderToken(sql.NotPredicates(p))
}
