// Code generated by ent, DO NOT EDIT.

package oauthclient

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Fishwaldo/mcp-docstore/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldCreatedAt, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientID, v))
}

// ClientSecretHash applies equality check predicate on the "client_secret_hash" field. It's identical to ClientSecretHashEQ.
func ClientSecretHash(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientSecretHash, v))
}

// ClientType applies equality check predicate on the "client_type" field. It's identical to ClientTypeEQ.
func ClientType(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientType, v))
}

// TokenEndpointAuthMethod applies equality check predicate on the "token_endpoint_auth_method" field. It's identical to TokenEndpointAuthMethodEQ.
func TokenEndpointAuthMethod(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldTokenEndpointAuthMethod, v))
}

// ClientName applies equality check predicate on the "client_name" field. It's identical to ClientNameEQ.
func ClientName(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientName, v))
}

// RegistrationAccessTokenHash applies equality check predicate on the "registration_access_token_hash" field. It's identical to RegistrationAccessTokenHashEQ.
func RegistrationAccessTokenHash(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRegistrationAccessTokenHash, v))
}

// RegistrationIP applies equality check predicate on the "registration_ip" field. It's identical to RegistrationIPEQ.
func RegistrationIP(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRegistrationIP, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldCreatedAt, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientID, v))
}

// ClientSecretHashEQ applies the EQ predicate on the "client_secret_hash" field.
func ClientSecretHashEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientSecretHash, v))
}

// ClientSecretHashNEQ applies the NEQ predicate on the "client_secret_hash" field.
func ClientSecretHashNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientSecretHash, v))
}

// ClientSecretHashIn applies the In predicate on the "client_secret_hash" field.
func ClientSecretHashIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientSecretHash, vs...))
}

// ClientSecretHashNotIn applies the NotIn predicate on the "client_secret_hash" field.
func ClientSecretHashNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientSecretHash, vs...))
}

// ClientSecretHashGT applies the GT predicate on the "client_secret_hash" field.
func ClientSecretHashGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientSecretHash, v))
}

// ClientSecretHashGTE applies the GTE predicate on the "client_secret_hash" field.
func ClientSecretHashGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientSecretHash, v))
}

// ClientSecretHashLT applies the LT predicate on the "client_secret_hash" field.
func ClientSecretHashLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientSecretHash, v))
}

// ClientSecretHashLTE applies the LTE predicate on the "client_secret_hash" field.
func ClientSecretHashLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientSecretHash, v))
}

// ClientSecretHashContains applies the Contains predicate on the "client_secret_hash" field.
func ClientSecretHashContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientSecretHash, v))
}

// ClientSecretHashHasPrefix applies the HasPrefix predicate on the "client_secret_hash" field.
func ClientSecretHashHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientSecretHash, v))
}

// ClientSecretHashHasSuffix applies the HasSuffix predicate on the "client_secret_hash" field.
func ClientSecretHashHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientSecretHash, v))
}

// ClientSecretHashEqualFold applies the EqualFold predicate on the "client_secret_hash" field.
func ClientSecretHashEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientSecretHash, v))
}

// ClientSecretHashContainsFold applies the ContainsFold predicate on the "client_secret_hash" field.
func ClientSecretHashContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientSecretHash, v))
}

// ClientTypeEQ applies the EQ predicate on the "client_type" field.
func ClientTypeEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientType, v))
}

// ClientTypeNEQ applies the NEQ predicate on the "client_type" field.
func ClientTypeNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientType, v))
}

// ClientTypeIn applies the In predicate on the "client_type" field.
func ClientTypeIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientType, vs...))
}

// ClientTypeNotIn applies the NotIn predicate on the "client_type" field.
func ClientTypeNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientType, vs...))
}

// ClientTypeGT applies the GT predicate on the "client_type" field.
func ClientTypeGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientType, v))
}

// ClientTypeGTE applies the GTE predicate on the "client_type" field.
func ClientTypeGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientType, v))
}

// ClientTypeLT applies the LT predicate on the "client_type" field.
func ClientTypeLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientType, v))
}

// ClientTypeLTE applies the LTE predicate on the "client_type" field.
func ClientTypeLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientType, v))
}

// ClientTypeContains applies the Contains predicate on the "client_type" field.
func ClientTypeContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientType, v))
}

// ClientTypeHasPrefix applies the HasPrefix predicate on the "client_type" field.
func ClientTypeHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientType, v))
}

// ClientTypeHasSuffix applies the HasSuffix predicate on the "client_type" field.
func ClientTypeHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientType, v))
}

// ClientTypeEqualFold applies the EqualFold predicate on the "client_type" field.
func ClientTypeEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientType, v))
}

// ClientTypeContainsFold applies the ContainsFold predicate on the "client_type" field.
func ClientTypeContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientType, v))
}

// TokenEndpointAuthMethodEQ applies the EQ predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldTokenEndpointAuthMethod, v))
}

// TokenEndpointAuthMethodNEQ applies the NEQ predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldTokenEndpointAuthMethod, v))
}

// TokenEndpointAuthMethodIn applies the In predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldTokenEndpointAuthMethod, vs...))
}

// TokenEndpointAuthMethodNotIn applies the NotIn predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldTokenEndpointAuthMethod, vs...))
}

// TokenEndpointAuthMethodGT applies the GT predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldTokenEndpointAuthMethod, v))
}

// TokenEndpointAuthMethodGTE applies the GTE predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldTokenEndpointAuthMethod, v))
}

// TokenEndpointAuthMethodLT applies the LT predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldTokenEndpointAuthMethod, v))
}

// TokenEndpointAuthMethodLTE applies the LTE predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldTokenEndpointAuthMethod, v))
}

// TokenEndpointAuthMethodContains applies the Contains predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldTokenEndpointAuthMethod, v))
}

// TokenEndpointAuthMethodHasPrefix applies the HasPrefix predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldTokenEndpointAuthMethod, v))
}

// TokenEndpointAuthMethodHasSuffix applies the HasSuffix predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldTokenEndpointAuthMethod, v))
}

// TokenEndpointAuthMethodEqualFold applies the EqualFold predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldTokenEndpointAuthMethod, v))
}

// TokenEndpointAuthMethodContainsFold applies the ContainsFold predicate on the "token_endpoint_auth_method" field.
func TokenEndpointAuthMethodContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldTokenEndpointAuthMethod, v))
}

// ClientNameEQ applies the EQ predicate on the "client_name" field.
func ClientNameEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientName, v))
}

// ClientNameNEQ applies the NEQ predicate on the "client_name" field.
func ClientNameNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientName, v))
}

// ClientNameIn applies the In predicate on the "client_name" field.
func ClientNameIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientName, vs...))
}

// ClientNameNotIn applies the NotIn predicate on the "client_name" field.
func ClientNameNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientName, vs...))
}

// ClientNameGT applies the GT predicate on the "client_name" field.
func ClientNameGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientName, v))
}

// ClientNameGTE applies the GTE predicate on the "client_name" field.
func ClientNameGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientName, v))
}

// ClientNameLT applies the LT predicate on the "client_name" field.
func ClientNameLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientName, v))
}

// ClientNameLTE applies the LTE predicate on the "client_name" field.
func ClientNameLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientName, v))
}

// ClientNameContains applies the Contains predicate on the "client_name" field.
func ClientNameContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientName, v))
}

// ClientNameHasPrefix applies the HasPrefix predicate on the "client_name" field.
func ClientNameHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientName, v))
}

// ClientNameHasSuffix applies the HasSuffix predicate on the "client_name" field.
func ClientNameHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientName, v))
}

// ClientNameEqualFold applies the EqualFold predicate on the "client_name" field.
func ClientNameEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientName, v))
}

// ClientNameContainsFold applies the ContainsFold predicate on the "client_name" field.
func ClientNameContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientName, v))
}

// RegistrationAccessTokenHashEQ applies the EQ predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRegistrationAccessTokenHash, v))
}

// RegistrationAccessTokenHashNEQ applies the NEQ predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldRegistrationAccessTokenHash, v))
}

// RegistrationAccessTokenHashIn applies the In predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldRegistrationAccessTokenHash, vs...))
}

// RegistrationAccessTokenHashNotIn applies the NotIn predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldRegistrationAccessTokenHash, vs...))
}

// RegistrationAccessTokenHashGT applies the GT predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldRegistrationAccessTokenHash, v))
}

// RegistrationAccessTokenHashGTE applies the GTE predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldRegistrationAccessTokenHash, v))
}

// RegistrationAccessTokenHashLT applies the LT predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldRegistrationAccessTokenHash, v))
}

// RegistrationAccessTokenHashLTE applies the LTE predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldRegistrationAccessTokenHash, v))
}

// RegistrationAccessTokenHashContains applies the Contains predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldRegistrationAccessTokenHash, v))
}

// RegistrationAccessTokenHashHasPrefix applies the HasPrefix predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldRegistrationAccessTokenHash, v))
}

// RegistrationAccessTokenHashHasSuffix applies the HasSuffix predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldRegistrationAccessTokenHash, v))
}

// RegistrationAccessTokenHashIsNil applies the IsNil predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldRegistrationAccessTokenHash))
}

// RegistrationAccessTokenHashNotNil applies the NotNil predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldRegistrationAccessTokenHash))
}

// RegistrationAccessTokenHashEqualFold applies the EqualFold predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldRegistrationAccessTokenHash, v))
}

// RegistrationAccessTokenHashContainsFold applies the ContainsFold predicate on the "registration_access_token_hash" field.
func RegistrationAccessTokenHashContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldRegistrationAccessTokenHash, v))
}

// RegistrationIPEQ applies the EQ predicate on the "registration_ip" field.
func RegistrationIPEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldRegistrationIP, v))
}

// RegistrationIPNEQ applies the NEQ predicate on the "registration_ip" field.
func RegistrationIPNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldRegistrationIP, v))
}

// RegistrationIPIn applies the In predicate on the "registration_ip" field.
func RegistrationIPIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldRegistrationIP, vs...))
}

// RegistrationIPNotIn applies the NotIn predicate on the "registration_ip" field.
func RegistrationIPNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldRegistrationIP, vs...))
}

// RegistrationIPGT applies the GT predicate on the "registration_ip" field.
func RegistrationIPGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldRegistrationIP, v))
}

// RegistrationIPGTE applies the GTE predicate on the "registration_ip" field.
func RegistrationIPGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldRegistrationIP, v))
}

// RegistrationIPLT applies the LT predicate on the "registration_ip" field.
func RegistrationIPLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldRegistrationIP, v))
}

// RegistrationIPLTE applies the LTE predicate on the "registration_ip" field.
func RegistrationIPLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldRegistrationIP, v))
}

// RegistrationIPContains applies the Contains predicate on the "registration_ip" field.
func RegistrationIPContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldRegistrationIP, v))
}

// RegistrationIPHasPrefix applies the HasPrefix predicate on the "registration_ip" field.
func RegistrationIPHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldRegistrationIP, v))
}

// RegistrationIPHasSuffix applies the HasSuffix predicate on the "registration_ip" field.
func RegistrationIPHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldRegistrationIP, v))
}

// RegistrationIPIsNil applies the IsNil predicate on the "registration_ip" field.
func RegistrationIPIsNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIsNull(FieldRegistrationIP))
}

// RegistrationIPNotNil applies the NotNil predicate on the "registration_ip" field.
func RegistrationIPNotNil() predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotNull(FieldRegistrationIP))
}

// RegistrationIPEqualFold applies the EqualFold predicate on the "registration_ip" field.
func RegistrationIPEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldRegistrationIP, v))
}

// RegistrationIPContainsFold applies the ContainsFold predicate on the "registration_ip" field.
func RegistrationIPContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldRegistrationIP, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.NotPredicates(p))
}
